package flux

import (
	fluxKustomize "github.com/fluxcd/kustomize-controller/api/v1"
	fluxSource "github.com/fluxcd/source-controller/api/v1"
)

// The bootstrap layer, which stays in git rather than shipping in an artifact.
//
// Level 1 is unchanged and still generated by `flux bootstrap`: a GitRepository
// on this repository, and the flux-system Kustomization that reconciles this
// directory. What changes is level 2 — each tier now reads its own OCI artifact
// instead of a path in the repository, so this file is the only place that knows
// the registry.

_registry: "oci://ghcr.io/joker9944/k8s-config"

// The tier graph. Everything that puts workloads on the cluster waits for
// controllers, which brings up cert-manager, MetalLB, Traefik, Longhorn and CNPG.
// plugins advertises node devices and needs none of it.
_tiers: [string]: {
	tree: "apps" | "infrastructure"
	dependsOn: [...string] | *["controllers"]
}
_tiers: {
	controllers: {tree: "infrastructure", dependsOn: []}
	plugins: {tree: "infrastructure", dependsOn: []}
	observability: tree: "infrastructure"
	security: tree:      "infrastructure"
	storage: tree:       "infrastructure"
	cloud: tree:         "apps"
	media: tree:         "apps"
	utility: tree:       "apps"
}

// One artifact per tier, so an evaluation error in one cannot stall the others.
//
// verify accepts only a keyless cosign signature made by cue-publish on main:
// the certificate subject carries the ref, so a run from any other branch signs
// with an identity this rejects.
_source: {
	name: string
	out: fluxSource.#OCIRepository & {
		apiVersion: "source.toolkit.fluxcd.io/v1"
		kind:       "OCIRepository"
		metadata: {"name": name, namespace: "flux-system"}
		spec: {
			interval: "10m"
			url:      "\(_registry)/\(name)"
			ref: tag: "latest"
			verify: {
				provider: "cosign"
				matchOIDCIdentity: [{
					issuer: "^https://token\\.actions\\.githubusercontent\\.com$"
					// Joker9944, not joker9944: the SAN carries GitHub's canonical owner
					// casing, unlike the registry path above, which GHCR lowercases.
					subject: "^https://github\\.com/Joker9944/k8s-config/\\.github/workflows/cue-publish\\.yaml@refs/heads/main$"
				}]
			}
		}
	}
}

// The level-2 Kustomization. It reconciles the artifact's sync/ directory rather
// than its root, because kustomize-controller's generated kustomization walks
// subdirectories: at the root this would apply every workload itself, without
// the decryption only level 3 carries.
_sync: {
	name: string
	dependsOn: [...string]
	out: fluxKustomize.#Kustomization & {
		apiVersion: "kustomize.toolkit.fluxcd.io/v1"
		kind:       "Kustomization"
		metadata: {"name": name, namespace: "flux-system"}
		spec: {
			interval: "30m"
			path:     "./sync"
			prune:    true
			sourceRef: {kind: "OCIRepository", "name": name}
			if len(dependsOn) > 0 {
				"dependsOn": [for d in dependsOn {"name": d}]
			}
		}
	}
}

// One file per tree, matching the two the cluster reconciles today.
sync: {
	for tree in ["apps", "infrastructure"] {
		(tree): [
			for name, t in _tiers if t.tree == tree
			for r in [
				(_source & {"name": name}).out,
				(_sync & {"name": name, dependsOn: t.dependsOn}).out,
			] {r},
		]
	}
}
