apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloud
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/cloud
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloud
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: cloud
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: media
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/media
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: media
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: utility
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/utility
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: utility
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: utility
