apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/controllers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: controllers
  namespace: flux-system
spec:
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: controllers
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugins
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/plugins
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plugins
  namespace: flux-system
spec:
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: plugins
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: observability
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/observability
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: observability
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: observability
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: security
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/security
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: security
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: storage
  namespace: flux-system
spec:
  interval: 10m
  ref:
    tag: latest
  url: oci://ghcr.io/joker9944/k8s-config/storage
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage
  namespace: flux-system
spec:
  dependsOn:
    - name: controllers
  interval: 30m
  path: ./sync
  prune: true
  sourceRef:
    kind: OCIRepository
    name: storage
