apiVersion: v1
kind: Secret
metadata:
  name: gotify-default-user
  namespace: gotify
stringData:
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:jv6IekU=,iv:1R0A9+BJ7pbpKGlMd7yMSsLjBi0eToDJf/CeyS1GKyU=,tag:P1yRaZJ18donJ3catbwdIg==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:Eq9azoPh5nK0BDbLGB211882vJhwxEGW,iv:EI3giCPUZPcPZKSOJomXA11Q+/rPvN7kq/QeQPz/UeE=,tag:RYbxXZaudiRnVlpmuzuNeQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhenBJMWtXV2U5ckVBdzRi
        TG5QVHJFekJUSHR6UHptaEltMmNmdUtHR0dFCkRFdEhjYkFiQTVRMXRnaVB2TS9J
        VjNieEk4ZlJ4WiswZEdkdFptYmV4YWMKLS0tIGVHSWdjdURhV0lhak1HV0FYY3ly
        b2F5WC9TanVCV0JpVG01bzFSVklwN1EK1k0QtxwYb59E77mHMZXpAMtjVp09SpVi
        MPqKe0R2J8EOPiQjvbF8ZaolakbQcW32XYP3s+p52emC70z19kAU8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:+aQpyicUuutjRhvXstLFozirxWcCgm9okT32vw7S+FpA/Sv7ttF0KaR8pe7a90NvP+pcg/Pdr5OjLAeqE4PvGrSmQnfW1eO4JfEn14dpPaqvbPQ18vXMEmTPetmyXQG50a7XxNUvppqgK+jvM5XQj8Qcm7UygXUcnhShcVYLnhU=,iv:46ogiv6tuOo0VOnZesESrNc813asZOIShFzLHpWdE9I=,tag:znDyaz8DFmmDiXGzlcRa7w==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-user
  namespace: gotify
stringData:
  username: ENC[AES256_GCM,data:fElMEph2,iv:yLtLbUqa2SZg1HyXjcXKSsaELM/IKmDMlGGnWuaR/Fo=,tag:LWrJi2TiT3mTNy3nxSyPhw==,type:str]
  password: ENC[AES256_GCM,data:mgI6nwKz1LjnFYMT0lVeNIz0sBWglpqc,iv:STE5fbQiudWkrKEGNIU9ClYlqm6l/ysSxEIDdNNmpe4=,tag:Ywkh10oZ2UtBVV7yf6OY1w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhenBJMWtXV2U5ckVBdzRi
        TG5QVHJFekJUSHR6UHptaEltMmNmdUtHR0dFCkRFdEhjYkFiQTVRMXRnaVB2TS9J
        VjNieEk4ZlJ4WiswZEdkdFptYmV4YWMKLS0tIGVHSWdjdURhV0lhak1HV0FYY3ly
        b2F5WC9TanVCV0JpVG01bzFSVklwN1EK1k0QtxwYb59E77mHMZXpAMtjVp09SpVi
        MPqKe0R2J8EOPiQjvbF8ZaolakbQcW32XYP3s+p52emC70z19kAU8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:+aQpyicUuutjRhvXstLFozirxWcCgm9okT32vw7S+FpA/Sv7ttF0KaR8pe7a90NvP+pcg/Pdr5OjLAeqE4PvGrSmQnfW1eO4JfEn14dpPaqvbPQ18vXMEmTPetmyXQG50a7XxNUvppqgK+jvM5XQj8Qcm7UygXUcnhShcVYLnhU=,iv:46ogiv6tuOo0VOnZesESrNc813asZOIShFzLHpWdE9I=,tag:znDyaz8DFmmDiXGzlcRa7w==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-connection
  namespace: gotify
stringData:
  GOTIFY_DATABASE_CONNECTION: ENC[AES256_GCM,data:rRkibrCcDTX1cRl1nU1m18K86WX3sptRqMvyRwzYxo/0rd2g9UbfQPFjbIphwqeW4y0ORHSl2+Lc3q8NpQhWE3TetgAE9hGggId7hr2fsrV0f7ZGmnTkWy/xqJnQopTyvoM7oueb5GEx,iv:dtS1o6mWW0cB1pLbUEQ9gzRKeRMUOLd4Xz2qymAWkN8=,tag:IRMXTthlwycp5Bo+dp5fCg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhenBJMWtXV2U5ckVBdzRi
        TG5QVHJFekJUSHR6UHptaEltMmNmdUtHR0dFCkRFdEhjYkFiQTVRMXRnaVB2TS9J
        VjNieEk4ZlJ4WiswZEdkdFptYmV4YWMKLS0tIGVHSWdjdURhV0lhak1HV0FYY3ly
        b2F5WC9TanVCV0JpVG01bzFSVklwN1EK1k0QtxwYb59E77mHMZXpAMtjVp09SpVi
        MPqKe0R2J8EOPiQjvbF8ZaolakbQcW32XYP3s+p52emC70z19kAU8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:+aQpyicUuutjRhvXstLFozirxWcCgm9okT32vw7S+FpA/Sv7ttF0KaR8pe7a90NvP+pcg/Pdr5OjLAeqE4PvGrSmQnfW1eO4JfEn14dpPaqvbPQ18vXMEmTPetmyXQG50a7XxNUvppqgK+jvM5XQj8Qcm7UygXUcnhShcVYLnhU=,iv:46ogiv6tuOo0VOnZesESrNc813asZOIShFzLHpWdE9I=,tag:znDyaz8DFmmDiXGzlcRa7w==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-alertmanager-bridge-default-token
  namespace: gotify
stringData:
  GOTIFY_TOKEN: ENC[AES256_GCM,data:m/KpTBHaR4Z/tY5fhjKT,iv:NbfWOaPfzZah1FXRfxR2a+5ysvZFd5/I61QuBzMb+qs=,tag:iNNwFA1o3pibw1UY4rRdTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhenBJMWtXV2U5ckVBdzRi
        TG5QVHJFekJUSHR6UHptaEltMmNmdUtHR0dFCkRFdEhjYkFiQTVRMXRnaVB2TS9J
        VjNieEk4ZlJ4WiswZEdkdFptYmV4YWMKLS0tIGVHSWdjdURhV0lhak1HV0FYY3ly
        b2F5WC9TanVCV0JpVG01bzFSVklwN1EK1k0QtxwYb59E77mHMZXpAMtjVp09SpVi
        MPqKe0R2J8EOPiQjvbF8ZaolakbQcW32XYP3s+p52emC70z19kAU8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:+aQpyicUuutjRhvXstLFozirxWcCgm9okT32vw7S+FpA/Sv7ttF0KaR8pe7a90NvP+pcg/Pdr5OjLAeqE4PvGrSmQnfW1eO4JfEn14dpPaqvbPQ18vXMEmTPetmyXQG50a7XxNUvppqgK+jvM5XQj8Qcm7UygXUcnhShcVYLnhU=,iv:46ogiv6tuOo0VOnZesESrNc813asZOIShFzLHpWdE9I=,tag:znDyaz8DFmmDiXGzlcRa7w==,type:str]
  version: 3.13.3
