apiVersion: v1
kind: Secret
metadata:
  name: gotify-restic-data
  namespace: gotify
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kBMnPFEMyvjMEGRfD+d4bixvDqhoOQAHzX0lXw==,iv:Oj5897HPRswsH/BFYPJgN4PTJ3Kk3HTjDWPoNVWxvjc=,tag:D5gLODwKXYx2dn0re5Vk9A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z4n5zBSjoqehsaXolczRszr1bTVPrdEi0g7VeayRTyQcby3cALqKLx5WWwRoJIZRUu5tX9g=,iv:x3HFbp7/qXUo/R/ZmXO9YaINGGy2U1cOKeFReT/MpII=,tag:TtsKbYF7i4bjVx4UkO+okA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:jc0lh+35yZdyHqcWEiX9y3VnkQs=,iv:f/S2kppuDue1NptxxWnCnQVtTx7q4LF1RJ430SHZEN0=,tag:ihMRzkgr/B8e7K7wKlZGGw==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:JMCIJY1CyY2IRwHywwfVq1NgL4MfUVywB2/alW2o0fIsgspPd8ewk9L/Z5G36qS3rvokErMsfxgW9Hs=,iv:nUoH8F4CIZ8KGlL65bzvJ/KMOkKY+nILt2rhG+omb50=,tag:GDOHTC6KdY9havBBgAtTTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdEVSWDRuc3daTXhBVDBT
        eU05UFphMTBGN0RTdWdKd2tDQzFmR0lDbFhrCldSdUVxTnZWSlZvcitwWXFISXBV
        Q0I1V01XTDl3bzNNYlRmQkJhQXNpWGsKLS0tIGt6L3ZqbXVYOGxSTnRXeHAxeUZ6
        L0EzZUsvOUYxK1lDTTZxZWhLRitXbG8KA183+Ne81Io6wxudqilLPF9jlw63UzIG
        e34WJK86GlL/DE0hcVvw3gEYRmwgPBR3hbNQClGTYpFw2XAgmLnFPA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:CzGn0HLgx4U7f5/unZPUbhXUcjihUM9fO9JOQB3cEVB34viOMA745qnK0wtfC+sNQBTMS7v0t1iLiRYBR7yoRS9RM5IAMQ8tz2NayBN27WvxiJDOYJmx4k5CqWhGHWdT/BFC0pPLsEtdIyRY5aZwcNjrYqaxLINZKtMO9WzQ8YE=,iv:IwgdPYxgLt9mAJKDmXpIDJl2ZhOnu9Qs7OqOhe2DXa4=,tag:FWXdVKIMSn82mWeSo7TC3A==,type:str]
  version: 3.13.3
