apiVersion: v1
kind: Secret
metadata:
  name: komga-restic-config
  namespace: komga
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:e9YNNDB5jfY7uXj6+XFmVCNfxpu2PXjNIa3zlg==,iv:FSczg/kMw2UXyb/ZeRQUD5MV2M/ScgmXwQ5Fa/OYWCw=,tag:qYi833u3IPi86jwAYeL7jw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ed+WimNDNZmuJDlJ6jGeruiS+idOqO2FvlGYkH4Hp+frxTMJgeOIFck6G1Q46eIjsYXAUZo=,iv:iciGEaIFxHOBqNj5ixRLnKRjEuqe/BngUl8jpSmAOR8=,tag:qoUGRMLh2AFLhfd9eddgFg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:hFpCY5YHZ1FZ7qfYxxaDIvEvzgM=,iv:baoFH1F2ZMOOG0yLY3UuVhEX8pu2FkcHIuAEBxV4TyI=,tag:vcmmT3bYmiX/xbjJOkPv0g==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:NPNWiI4in4IhtywfhdzHGiZGX9uOvBRZ8UdGSyPnBYmLQuSW2o5C8PSBz2D1sFVogPHVk16aGHfVCpPO,iv:eR4J1JP9JoW18AQg/V4X3CJw/9DvqzLLx8/VuqYYsGM=,tag:tPQM6u1lu4IF/O8RKkaWSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWWw3d2cvbnlBSHFuOEYv
        OHRCUFVoTXhlR0ZSc3VVbGoxUkthNTJiS1c0CllIaWVGUWZPbktzeS9TNFBIU1Ba
        Yk84NGkwRzBDQ09CL0FrVmlibXk5R2MKLS0tIHlIMnhIUlhUcytXYStGUTlKMGw1
        UlJ5WCtmeEt6QndzM2hFTmhRZEFKZTQKiocKwBT6ODXjDGAEb19Rt+zKZTR4nBCq
        LxHof/6LLPmRiwJLAPcrbt4BmLyAODwtEmVWUaMJECQ0XphiScrVPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:Q4t6Tivw/nSK5RR4xmzIdq/KcPdFEhnw2Viu6DcUqkU85h7v2pmbhbLkED90LjOXguG5OkA2ZswAiTFndr/QKwSvooZneaAFzfM3mNdjdEOSHzoTV30RvW2j7jEOt5wLsN++G0exvcrMn85X0aG/0D3b9Cz2/kOyi4VbEFwqP+s=,iv:zIbeSKOEqeufn5rKGTHZ7EOxj+ldq9esnPEHUwu7uWE=,tag:FcpY+b4IYTX05jkYPn7vUg==,type:str]
  version: 3.13.3
