apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-credentials
  namespace: pgadmin
stringData:
  password: ENC[AES256_GCM,data:EssT+urTrn3k9eDP0w/8AAJExQU=,iv:C+ovF6wrBAU6LF7r295SngTlZgyAANxtJIF4cqZI3yA=,tag:ZuY7M3DWLuIUioNIhJnVlg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUWxEM2V0c2ZCdExlRTlk
        Yk9EaU0vbmNqTmdlMTZhc1BML0VHOXBUQUhvCnZUUDFncEF4bWUrUDFWNndLb09G
        VGdXVWs2WUNjSXp6UE8wQ3JITFVKYjgKLS0tIGlqVnlDREtiNndJRVZiZGU2L3Jt
        bGR1aXhabHd4bDdxa1BCeTkwdVJmL1EK7R+31/G0KSviXn3QOz2eTTkDZQp6avSh
        6rA2asBjnzoWMA10a7+DW112HLOtL+UqpLHLRJvW0sKlu+B0qbdOWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:34:08Z"
  mac: ENC[AES256_GCM,data:USzaJMC32CXphU57b5kFA4gRj4+kSuQ/2JZiHxMy1NGQgdRZz6cqZhWU+ou4YQU+VRLdEA55xrqHTN5JFUXcD9WT7PEv2oW/adRJFXMZ8I0FC0B7SptIE5c87lhijx1xxblnQHA/L78FqQAu0kIGhxgQd8daVyqF/2KLy7DJdmU=,iv:4YexJWwghFn7tfAlysiSG0cIXcJJAIy0fNrjdisk/uQ=,tag:AZ1TAjhDglBEpfENghXLqw==,type:str]
  version: 3.13.3
