apiVersion: v1
kind: Secret
metadata:
  name: traefik-oidc-redis
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: servarr
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:BHrqB68sUxnbGQ==,iv:tLfJkbnlgu5m0/PzlPrHw4DS+B4ue9iCS+nTAue2K+s=,tag:MpwP5BF0FNJlwz/gmyzvcA==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY2NING1rdk9aaThscVN5
        L0ovR0pxOWsveDB4TmRaeE1QTVBqcE04dHdFCmk3Z29wLzdHeWN0WGg0d2MvaXVQ
        NldjZzJISjNjWlVMTEUwb1JkdHc3YUUKLS0tIExyZkxIL3pKcDdYamp2VTdxTllJ
        MzVZQjVGVzhVNjM4R2pEVlp2S0JZa0EKIim3dXCo2IAvo/cVdgXeo0na2dxC2khl
        MlhZTRIkHDZuGj8iI4QIX1itcYUyABKLbkKOixVj7T5X9iQfS72m3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T12:39:35Z"
  mac: ENC[AES256_GCM,data:kazpUwoDc5s8vPU70dD/v7WB6LZBuaLq2Wk/DKOg0eZaeH/GoL6C/RGdTYri1LMNxZdj3A8L9TCxoa4Gho4feqCZs9hKkFH11937Sq00Rps8rvG0htDflqJ5pA5priqq8fx5LDofcKxey208EzlXnJ96wO0ANETOKdoabMoTt9s=,iv:oFReOp06D/EV/gneAfxL9/p3XvRreE3elc8w9B2qhQc=,tag:cmTJ5J0R3L8Fp8YxlGpUQQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
