apiVersion: v1
kind: Secret
metadata:
  name: traefik-oidc-redis
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: servarr
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:6tXDeQAIS+mhfA==,iv:ZnJX0Poca4Ba8FIb+K3iSP7ZQEPt8LUxIQqhOSQEB0Q=,tag:O5P9a+br+CaA3wSN3Ae4Iw==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQREp2elRMcVBIclkrQWQ4
        aDNQRXNCakVVMy82bnNTRytWNFY0YjFNNDI0ClREWjZGQW1QZG00eFllcW03SFJk
        bjBtaEduOGpOMzh4ZFJIWnVIZElEUzgKLS0tIFk2cHlFZUJyQlUzT3BDeDczVC8x
        dXZESmVGQkFaN1Rtc1JEQjFHV2I0SWsK14xPeX0XQ8/MxA/KS7z0K95TIK8Hs4cC
        VecfmytBu8mZUEvZYSX7td3nzX+wEtqIvzsMLp2ePulI5McxwoW7dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:10:51Z"
  mac: ENC[AES256_GCM,data:KRT/Lmop9DoEUdhDzDX6zgZop2traqWVwsd4jcGAWQd/7lpJuA7/04fgr0qf3v4H+w/1higEjeMD7dEcWGy07g4D6VdqB7ERzEixo9iCjbzeB55gZPth3xSvUbKl6bWAaVfawn3U917q5GTQPX+jMLgV88Wg0qidJ5DPQwkPah4=,iv:O2c2baXqAnJwr5B/992fEtBwajfh/Hp5qwh0t07zFZs=,tag:WjEpWkeTVUozSGjOZsgvkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-geo-lookup
type: Opaque
stringData:
  ACCOUNT_ID: ENC[AES256_GCM,data:5zTHwOHk1A==,iv:8UPf2xF+vqkVUcGNyh3bEiXbZYUlcDM8pAALiy2X4Fo=,tag:Wjskwxit8N5gpMRQ+FKSKg==,type:str]
  LICENSE_KEY: ENC[AES256_GCM,data:2LqhAXWdOiC1GYFMVWzJoHHPE2wScd2dreWi90VOyXUKcwJidFvcAQ==,iv:IoXFWgnGKdtksGmbrVpTlvqWWHc8HOQN7usCcsx3w3M=,tag:OxzNxD4Pz6oRQF+2HIBO2Q==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQREp2elRMcVBIclkrQWQ4
        aDNQRXNCakVVMy82bnNTRytWNFY0YjFNNDI0ClREWjZGQW1QZG00eFllcW03SFJk
        bjBtaEduOGpOMzh4ZFJIWnVIZElEUzgKLS0tIFk2cHlFZUJyQlUzT3BDeDczVC8x
        dXZESmVGQkFaN1Rtc1JEQjFHV2I0SWsK14xPeX0XQ8/MxA/KS7z0K95TIK8Hs4cC
        VecfmytBu8mZUEvZYSX7td3nzX+wEtqIvzsMLp2ePulI5McxwoW7dA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-31T16:10:51Z"
  mac: ENC[AES256_GCM,data:KRT/Lmop9DoEUdhDzDX6zgZop2traqWVwsd4jcGAWQd/7lpJuA7/04fgr0qf3v4H+w/1higEjeMD7dEcWGy07g4D6VdqB7ERzEixo9iCjbzeB55gZPth3xSvUbKl6bWAaVfawn3U917q5GTQPX+jMLgV88Wg0qidJ5DPQwkPah4=,iv:O2c2baXqAnJwr5B/992fEtBwajfh/Hp5qwh0t07zFZs=,tag:WjEpWkeTVUozSGjOZsgvkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
