apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-gotify-joker9944-url
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  url: ENC[AES256_GCM,data:c6eeU+SMDRfPFfXGmkSm33fbp6gEHgmLpOdXsic8apwF8CqzHfZTDiD7+JxppaxCmMddUnUaCMn2qTOsjUXnSL7JHyB+/+kRh1fe7eZERqJiwN79/jwnnaJDTw8SdaBRhNZ80PH6fplRi5yNhdrQqK1MyWXyQAgi+24=,iv:219Qjt9DQgbebt4pIJNTFcMA1dEujFZ7AQPi2Y80AYI=,tag:8fNSf9MnF2CjfO9Pwd6UQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRGJySmp1a2hqNUFRaUtI
        VXJiN0dqa1VWWnFyZFBBM20wQ3pURUtEYXhvCnF5Zkt3SVJIMWttMFg4M25FQ0lD
        M3pYUmQ5OEVvL3NYL0xMaG5CYkk1bUUKLS0tIHRZcmdrd0dwcnlxS3dUbnVYTGJB
        aXRqbFc5RkxwV216YWhpOVhUZm1LVDgK0693r4gW2BRmNcxHYoURZs6/ZMwdRvpc
        RKuOJ3qHSWZ1VOi9453RMb+G5ecBwHflQta5ahqQ8Xm1/yiXDHEsiA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T17:52:20Z"
  mac: ENC[AES256_GCM,data:bEyzmZ+Iu9RFHqtItWU3i1wiAXGgEQdgy4nNQybVp54ELaFauss/wcdFR3ifgIcx0/7aiQPLzBgYIZCDtBcQ+7e0NquHzCpBkYMx5trfPfrX0L2pBUagbfHpnzLSlotiz89KAGAgdNRZynqBL8ip7cV92A9YXTwxkOxxpxUyEsM=,iv:HroOlkCrKLItrlBbr1ODyjZJAwe5tR0WOcIP1vS45r4=,tag:raBNWTv1uor34EWThviFwA==,type:str]
  version: 3.13.3
