apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:J7VUAkM=,iv:8Qa9BTrb7ixYHjN2qBLoRhWYIjE+PoQNE58bSjPhCC4=,tag:2szVY699/X5WR0D14n1baw==,type:str]
  password: ENC[AES256_GCM,data:snC+Q1F2+nd4gqj2gFDkS2B6/7o=,iv:clemDkTry00Xq2RDEyKN0A09ZNtLWD8VwnsCsUezRnw=,tag:Pd5mCYfcZSuVFW7/RD4AgA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOFZhSEdGeVVhWWd2djBY
        UkJIbHE0VDAyQk9Kd1RGS2xlVWR6b0JPb0dJCnZyTFhMOGZSV29aU0pka0UxNkNL
        R2UxM1VpSGdiSGEvOHJOY2VKelBhLzQKLS0tIGdPUVlwc2szcmd2MmdHWkNYalYy
        a251Mkp6NW9OK2ZoL05lcG1kUHY5bm8KR3dYBGBZi7SMHsck4y4HD7QDoWJrVSoA
        neJGOaqXvn4Jaergw3Vfp0ZLFxF/kIxYC9FBEemPg/Qu1lY/ARl/Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T14:00:23Z"
  mac: ENC[AES256_GCM,data:Djtkh1GO8l1kcWKm2J8HMVr88CFlmSvHl6enMatBWtchFVNO0ao127mxAKAzy3KbeA5bmEEUq+542S6wwEoOV69MOS0Tbg4foEXY4VCpjxNHkYEsPm7lK0DtiiV/dNZ98k1qNfhsiU6x5BDUabqUO44N2Gvi7cDsuSRbVwF1EDo=,iv:N//jvkV5AjcN3LDibOd2qr0+CzWCSkCQ3QmPCY7EdME=,tag:U195vhbUj6F6I7J8TBLF9w==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-environment
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:k+baF5S7H3xLytR7rTSfgdynqCD0iubeqFfWKSbXwJtLWx2IFJO9vFSmL0DiWJUV,iv:anJl6bof4TQHyW+BQ6l8znP/czSpbuJcz9ujYNGlUcw=,tag:HCgGsTtj8V8sHqxt+J8LQA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOFZhSEdGeVVhWWd2djBY
        UkJIbHE0VDAyQk9Kd1RGS2xlVWR6b0JPb0dJCnZyTFhMOGZSV29aU0pka0UxNkNL
        R2UxM1VpSGdiSGEvOHJOY2VKelBhLzQKLS0tIGdPUVlwc2szcmd2MmdHWkNYalYy
        a251Mkp6NW9OK2ZoL05lcG1kUHY5bm8KR3dYBGBZi7SMHsck4y4HD7QDoWJrVSoA
        neJGOaqXvn4Jaergw3Vfp0ZLFxF/kIxYC9FBEemPg/Qu1lY/ARl/Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T14:00:23Z"
  mac: ENC[AES256_GCM,data:Djtkh1GO8l1kcWKm2J8HMVr88CFlmSvHl6enMatBWtchFVNO0ao127mxAKAzy3KbeA5bmEEUq+542S6wwEoOV69MOS0Tbg4foEXY4VCpjxNHkYEsPm7lK0DtiiV/dNZ98k1qNfhsiU6x5BDUabqUO44N2Gvi7cDsuSRbVwF1EDo=,iv:N//jvkV5AjcN3LDibOd2qr0+CzWCSkCQ3QmPCY7EdME=,tag:U195vhbUj6F6I7J8TBLF9w==,type:str]
  version: 3.13.3
