apiVersion: v1
kind: Secret
metadata:
  name: dedicated-server-abiotic-factor-restic-saved
  namespace: dedicated-server-abiotic-factor
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:eOjmrlizJF7q8DG15puRFSsl/lOekFYAU+2lGg==,iv:nBXhNVT5PBcOclJYlVsTZ9QqUMyf6Zz5BuHZWBxlAl8=,tag:NqJNL4hJevq4akjkLOICAA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rrKkp5Be/jkOS3jEr83w+E1SJWszz+8R/ILdX+UyL/LUsohUyp6X4a8XE1Bt3YlDTyIAxqI=,iv:7ygfPX9enX6OGQuzOVvAY9BFnCVg2ytpVHH32FaUd4s=,tag:nRP3EM7VmxvlK+398MSdAQ==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:xpc+P4s1vWpYR+je0PFMtBmwspM=,iv:mTufRvLWwne1p+lggC3ZSV+mi+g8X0PbjtMk55wu7L0=,tag:IQqrmkPifMhov7nc1ydedg==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:P6/KY3JgHBhUu2YL91QWB1D79LYWYjQwhJsEQSXeQg/18yoAC4dG3DegDB0XXPJIOleL6MWtCzzWDFMzXKrgjl0Sp9WTyWThwBs9E12wYgR4ujUuQw==,iv:sTziJkqsEe2T1yZv9BAVhWOjo3CpywfwoE8VEX89WMc=,tag:NKaIdcOczuNpqX52KIoSkg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcVkyRFB2bVlZcUxhR3VH
        OGl2ZWl1Y0ZxWm9XaTFveGVLS0tlUnlLYUEwCklBMldlcnZiUzU1SXRQZ2xXdFhT
        SEE2Z0V4SVp0SFkwanJhb3ZKaERQa0EKLS0tIGwrRmt1VVAzcDZuZ0JDNWQ0ZW5u
        Sm1KZkkzYkZQTVVHWmY3WUd2Sy9IcXMKlkSTS2vEcMduOYk+KduZ8TyaxJMRihff
        fQ4whHdza0UJuwz0G6LQyng5Dc9p9Grlap6e8ouRdh30Mw3qDDi8dQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:Sax2VoCFisw75s7khgrQ7kOf3MN5jFXSx77cw6FGd1QBa/38CpuED08e1wyI4HboWoMiky/D1FPpxBaMgLH9mQ7VY41e2OMEM1hLWcRqQBV2ZJdD2lOW5QyH0Ji4BW96SJTTWZ1X78RlEQaiB/+8DUnz9WYg3GryvDM1BWPXlHo=,iv:vUJAs3L02VxYvqCljo2ArE8VxvlQ2aHnjGDV6h37FHw=,tag:oHgEs1W3ZfKnNJqvz/sgBw==,type:str]
  version: 3.13.3
