loki:
  storage:
    s3:
      accessKeyId: ENC[AES256_GCM,data:nCwZah65ko5vyTj/T1cHUlKoSyVNEBzKRzs=,iv:Z0lcmhHdpBWxX1P9v0wA13YMSbiXX9tCDRicpKuFs98=,tag:2jzFwlp4EsQYYy5ce4grLw==,type:str]
      secretAccessKey: ENC[AES256_GCM,data:rMzrSR7K2/mU/i5Dasfc6fKZPhWFD9utm/hs4CwHKkl+SL+LZzcO2HI8FVrB6hAZj3CTe2wbe0AJ64uPLChC2w==,iv:ObU+Ct+gWa1Rkz9MeSKCPvZvkt5oXjHjWHBp/wX1f3o=,tag:oEjfrj8F/mUW8HmXXRNHLQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeFpGTUcyZzJ1NkFVbFYv
        dUVHelBJQmgrR2JDV1NORE1DMnZ0YlQzSEZjCm4zWFVpL29xTXp4UFhMN1o5QlZW
        b0tHM3FuZnA2N0doYlVRT2dUOHFkYk0KLS0tIEpBWFNmT2JaMWhzclZvZlJBSXcv
        eURhdEFwdTY0ZGhYR1FpZDhjUlNWWkkK8mZRO+907ztxxdlgdUOl3fg+ILbZLwD1
        T2yOWKdMt2UqAxMuv6YyspBoYpvODtc6pqh6Zs44Prl/nJ5pUP17iw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-23T21:50:14Z"
  mac: ENC[AES256_GCM,data:lC/RKZVSy5d4B3C+2nYhCQ9I80vk/mCreYdfoFrtp6V4jOnbgoRuTISr8dG2/6hf1SVyh+OQkLg2NZj4SOcwEusu4ync4U1hSNYKZ+vkl/bRDORWbXjBUdgNa6TeN40witEze+9Jhqxbu5nQ8Q5KWtdOTm5MKHhZ2+oJp2PIT6A=,iv:WVA3VC5kIumt296/6GPranvja21t/jbY7jyFoUWY9Mo=,tag:3Zqyfx8VLm8z5oTik3o0TA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
