apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-restic-config
  namespace: jellyfin
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gGo3QrUmLM6mqk9XLCcv8PWftUNyQ0Wizp9XsQ==,iv:/cVQ6azJewBMOgsQ+SJvhnQL9lCQS89INnBAqaeRvc0=,tag:V3fsikKbfRH9cKuzf0nd2w==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aAO9Me8vSDHBQFSBXOpQCvVEk1v4BPssWrD9KJ9va6vTsZRqIzVudf8/pj77b3+w1b/+pRs=,iv:6OSTGzwplw+Uk34UcJcK7xJ6iRMv9AAxB8euc+Va+/E=,tag:5tbgy4/vLwrIWpPULbWKoA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:jcxKdQ2gLfnb6Orujt/CLJObe2E=,iv:zoChQ3eP5IPJsZBJ5rqxm+C1L3O60eAc38SC2+UCYH8=,tag:NVYwhJ0pQl8FUGqP9RxS5g==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:yLKS+/rXeVZCmwWZC1x34OvbUuLH6c1TEulhGUSj0ivefiXWwAJQcaBywsyYUt00lKdGlWig9u9vIvaBS5FN,iv:cVcEpmI1LdgI8Ibpp6kgKpR+mI4MUwJhpHRGHYckVco=,tag:Id32i+CHIV1RMoc5NWf3cA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaWlkZG9VQ2NUMlZ4WXBO
        Y3kyUkl1aEpSeXA5My8rMSt2LzlWcE8zaFZZCmxXTlMwcDZ6UnA4QitwL0pWRGc0
        VVVpTjg2QmdlRzM0QXdNeHNrT0VLOE0KLS0tIHV3cE1xTHluYnFoaFJwT1hXeDB0
        a1hVNyt0WHBieHJUY2J4K1dKc2VRM2sK21YQ6e0Y8Hn/V/EnXzhkT9yFXs+pgL/V
        j5RZJqpgGvFia7dF7wPW1Oev5RRxxv2LgUNLySmBuSVrRWDjCbZ0yQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:04:06Z"
  mac: ENC[AES256_GCM,data:GxI/H3j8ikxOFYXFiLZWLPyTjiSESskL/8AGZddQqUX5rBH0CDNrzg/PeEu7yrWXgF8vSwP+FDVQoQ8pRJMt0j09uKOmrF+sJ1uWEVHqmedjE/mMgur5TC3uf3J5asVd/8WUxPJiKkvLmYKr/gUttR/49eTrYoVCr2OTyPMOdco=,iv:CGARg8obmidDejAMf0fF2A2Oboqo2u4LEcvuXM5OfyU=,tag:MChk4ZeCU7Im9s6OXy/Lnw==,type:str]
  version: 3.13.3
