apiVersion: v1
kind: Secret
metadata:
  name: dedicated-server-abiotic-factor
stringData:
  SERVER_NAME: ENC[AES256_GCM,data:GAAL,iv:j28RJtblJa3Uo6YM2/IQv+6lpY9izAnGdP3+AbGwziY=,tag:yqGe2VFt6tzZEp7Y9IMYtw==,type:str]
  SERVER_PASSWORD: ENC[AES256_GCM,data:2Lwh7vZl,iv:9UCOm907W+FuIamWw4P+Cjr6fJ5CMHZFQO84hEj2vxY=,tag:oZD8XKDP+BoDi/w76GBS5g==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwekpKWGRtYVNsemRnMFBz
        eSt4OEYwSlAvSkZCaHdJWTREWFpoNWE5K0JBCm5iY3dSUjFMTHUrZU1vTTBsbkp4
        bFBQcUFlemxTaCtieXJtTVdBcUFGMVUKLS0tIEZsdEc0NDNiL0hZY3BSNFZLR0pV
        RWRDMU0rRjZTUGsxTFQzWC95ay9HUDAKL5BZ/F+6bS/kKZVM67ykKLmIWUFShHy6
        IqU7ombZnv+I4uObIgkGLGPfWTZ3KyXO9zj+KGQnm1Zv3Z2JtQQW3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T11:43:43Z"
  mac: ENC[AES256_GCM,data:x3EvOm4mAO2wT2KWISKqHHtv9m7TqHTv9B2FBNVA6muRIfv9gpeliE9F+bWDJU44PziW2ac9D3iZJx3iFoOfuy4K3JnRlZGJiD3M5n/gIlQ3V9+SvplNKUGdidMyl2fLyea5+RNM9j7c/Qox6MfaSp2PI1SONPtEKsSnaAHFABM=,iv:wFj810rfhiMVufWVrTpjy71wQAUEZP6bId8+07cuKJ4=,tag:JuXt/Y1csZjW2j0J3ECApg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
