apiVersion: v1
kind: Secret
metadata:
  name: dedicated-server-abiotic-factor
stringData:
  SERVER_NAME: ENC[AES256_GCM,data:+Tu0,iv:ghjYeERTxNXNYCuWOxVUU0C2BmmQ/HsZ4DlaRtNwYoY=,tag:/CbrlfPawZGUdZlVkcU4qg==,type:str]
  SERVER_PASSWORD: ENC[AES256_GCM,data:W/HuS+LJ,iv:1GJL43p+2aRzfavhGentaurrifmiyLBleVm8oC+duko=,tag:lJ1Dm3B2hQqT/VGWFZreag==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RzFReWk0Z0svUDVWc1Fk
        RldwUFdBR2E4Z1VvVGRQQm9YQzVPVHlyRkZRCkx0UjdxT0ZhVWtTRlRObWJZMEV6
        aEgzMm1lNEFmSTFSRzl0SklJVFhubmsKLS0tIFJNci9qbzlXaWlmUEE3ZEl1Z29N
        dWtnYW01aDZNbW1rbWxYL05ybFlERU0Kt0eXdorWyGgDIkVgEfMFeW0hDmqFPNzN
        HnzyjyFQRQOyAdGsABF6I463D42O6fBFMA+8mz/v9zYKoQzhz0yUyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:13:32Z"
  mac: ENC[AES256_GCM,data:ptSLzc38Oafza1foA87oGxtww52EZT3J3VVV7MeGRutT7PQPBtHBF/48k1zw0Hg0lshRac62nu52FolO76PStAEHTc2EfmXQrOov9/C7bK00tC+Lqd5YGQbpRlmHWwzGXJoKql5zqmcXwY09egzVdMaQ6VprqckM4BvnwlFT510=,iv:hFUCoGb0dD/GTnCorc8EiqrhYG7gKfoLv/yWWzwCuv8=,tag:n+nUydwxf21NbSPa6xgA/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: dedicated-server-abiotic-factor-restic-saved
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cuTiHzIWxa10Dz121g+SB3DXaSsBmSbJHKo+yw==,iv:FY9uPMDKt606+NxvzrokBQkOYYvT3cOGgv79cU9T5fE=,tag:k2I52KlLrnawVsebOYNejg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:QvUU22Oef9Ab4z46StLg0jEErfTnN2EWhV/JRFshnhW1qi3ssdvEvNnIF5oZhb9NP8/7AZc=,iv:E/fa+SwuOjFh5xQtlPGUPZMEHoAMhpEUwE4XTnkNM3Y=,tag:cH43pDizGWtlIjGZsHENIw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DiwX4MSdFzOc4Rxa9rGXVGrjrXc=,iv:oUJUPZcKb7tv4Avu+DeaHaybxzsHrrrnI0zm03G+xAs=,tag:K9PBcNd4uEDT4abM57vuqg==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:pVxQlqj2WbIaIAl91JeiVG4C/DDjznOCqpGzFiLmZMhukkVTOSYf9bVMf5dC52QKm6HbLDbdlyYuhSgeu+o/5BiuDn9a7sVPYFOWX322kGhQhGR1Ww==,iv:SwA6yA6gWoO9i8QRwy26CdRtLbEnOZp/IV/67hB6ZsE=,tag:jdSfputAG+lmKVDUeStq1Q==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RzFReWk0Z0svUDVWc1Fk
        RldwUFdBR2E4Z1VvVGRQQm9YQzVPVHlyRkZRCkx0UjdxT0ZhVWtTRlRObWJZMEV6
        aEgzMm1lNEFmSTFSRzl0SklJVFhubmsKLS0tIFJNci9qbzlXaWlmUEE3ZEl1Z29N
        dWtnYW01aDZNbW1rbWxYL05ybFlERU0Kt0eXdorWyGgDIkVgEfMFeW0hDmqFPNzN
        HnzyjyFQRQOyAdGsABF6I463D42O6fBFMA+8mz/v9zYKoQzhz0yUyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T20:13:32Z"
  mac: ENC[AES256_GCM,data:ptSLzc38Oafza1foA87oGxtww52EZT3J3VVV7MeGRutT7PQPBtHBF/48k1zw0Hg0lshRac62nu52FolO76PStAEHTc2EfmXQrOov9/C7bK00tC+Lqd5YGQbpRlmHWwzGXJoKql5zqmcXwY09egzVdMaQ6VprqckM4BvnwlFT510=,iv:hFUCoGb0dD/GTnCorc8EiqrhYG7gKfoLv/yWWzwCuv8=,tag:n+nUydwxf21NbSPa6xgA/Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
