apiVersion: v1
kind: Secret
metadata:
  name: loki-s3
  namespace: loki
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:DMJYX8KJy2IAdvAlg9pHsPXFE+JRyYHWCKo=,iv:c5WqRBImMpdrCdQhgiUO4+J5G32KqAqDSkVWgmSvtBU=,tag:+7fz2NTUJJg1qIGd/HRyRw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:eu0cQSo17dM2QG0MeOdV889fKs/WnJuE56IvsPxTVrZWptjMxt7StYQNj0nrlya21yppyARQK4VNY0F/t9tn5w==,iv:slIpTbY2TqZIuTecPwAaGqVtH7iiQPmhIu9ZTKwtLuE=,tag:a/ZINq1qiAlRVP1n3rhmGA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYlFaMWxtVU9uOW55Rk9o
        WTFwT3FBa0FWNlprWXNlNzRVVEpWcGhPbDFRCmFwVGwzREdMN09xUU9PSmpFZm5E
        aExIOFJpY0YvOCtSVTdzbmU5aXl6WjQKLS0tIGpVK2FLdUxLLzNWVThKR0FpQUQ4
        cjFOZzhES2pRVWV1eHpwUVJMWU5YY1UKM1GnBfADhHVE+yAw6YmfiJFd0d33rTN+
        f0G6NOvv6QybUtcf+k6P0CXTG8kNDgLsrTL1xvxlRWNCwR0G8SQ+NA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T09:21:45Z"
  mac: ENC[AES256_GCM,data:VS/m1p1ETpHaFAIU9gltdCa5H5Picqhbz6TIyGGdYiTI0uhQTsstRlDlF4ZN/FETz+LZuoqAxtH9PGTWFx6tcUOtLp2o8KDJMoqTuRE6oxO9jIO2Lfb01UvGqUIFg3k5IcUit86+orGKa6v7IVdjw2KPRSsAyyhOPQ3SAu+cGzA=,iv:TUdcrT5NWnhuKiEuJMIglUx29Tx2Z7lhOUox1nwlDhg=,tag:fyt+N6LJreDaWtUSLsOHkQ==,type:str]
  version: 3.13.3
