apiVersion: v1
kind: Secret
metadata:
  name: gotify-default-user
stringData:
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:FydQWTo=,iv:xFIZvQ/e64udlWdjnelILY5+TP0rkWh5B4eG5CUgyJ0=,tag:tWmjPSzyqT+gTnfmq5QzPA==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:aWBAtmNOizsggSaBGrrxsdYZ2fGpA0ye,iv:lb9NYbdtIm897Jp8q3smdytUSDRW9lkaOA6AYq2p2W4=,tag:OAd30ANiE2I764xWiKCy2A==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5zaytGRkRnZnpVempE
        aWV1OFNEMlM0RFkram0xK3QrKzI2WUEvbWh3CnZwakF6NDZENTZrVkpIcEM1cEpM
        TUxZMlhyOHdueGZsQW1yRjhHcEd2eE0KLS0tIGlGRlJDNWowZTBTUmpnTHdIK1dq
        M0RNdzRKLzVEZUVWcldPRW11bVo2MHMKoGEjcJNVz1q6mjabJAz8LffoKubQu5m3
        5FxdrIgawI5hEvmzK89As2PoiEskXLaLQOUZTLBEWFqUhO3QixqHfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T22:45:38Z"
  mac: ENC[AES256_GCM,data:WzoRVzPnsbOSvOLcDYO3cXW9tqWVqwI8AVNvZ9U9j6qs9FVMqm7RAi+a5j5FpmqBbxsg7djLqYiy3kw3Oo0Pbtn/nvc5I73ODTnfspbySZaUwGuQVcC80Y4o+3Zpa97q6X66cs6N+fkJmm+ETypxVq8SYF3Jjqbl7qDEtdLzLJI=,iv:Hub4h3PmFj6/TdNNhZFBtnAk2hf73VhlX9+MplmPup0=,tag:7AcxSaGKGDLLBdgcKqM0YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-restic-data
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:oq5GxgrIPFbPQQiC7LMa1zgtOBStWx8VtGUVug==,iv:PC+fS/k+JNJWfItG3EdJaQ7DLDmoLtemvCbnoSZ/vkw=,tag:6zBN17nSJR/gn3WNG26N5g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:DV71Hsw3CvZHFU2uP9sk36RU74P+9atMhYr13n1+IhzZBrNSRSWbqi6udqMFDSgOUNaKtlE=,iv:SDPW3cnv+afJUBwCq1Jh7HIVTGULmx0bjBxYE9dhq7w=,tag:9Of9oGgIwQqmQfzhQpiO8Q==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:aGbPdc7ZX/gheNcr6hJmU27lqPc=,iv:4gvTisY41wGm3vymLw2LjWA8VGhkDanuo8gNR9yZ1qQ=,tag:KUuxLtIlMgnz4ewIagsm/A==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Rw5hZk7I9jCJoYPRSc9bljmi5lgCK1rBLlffo1yw5mDkVo663jltsZWX5r5E7KIcfPf78AF1pUON60k=,iv:OmlUcelszAlx44M2VB+AJbDTahdP+anOSpq3RYTzB8o=,tag:N4vFqOTFs5Bv2MogUSUyPQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5zaytGRkRnZnpVempE
        aWV1OFNEMlM0RFkram0xK3QrKzI2WUEvbWh3CnZwakF6NDZENTZrVkpIcEM1cEpM
        TUxZMlhyOHdueGZsQW1yRjhHcEd2eE0KLS0tIGlGRlJDNWowZTBTUmpnTHdIK1dq
        M0RNdzRKLzVEZUVWcldPRW11bVo2MHMKoGEjcJNVz1q6mjabJAz8LffoKubQu5m3
        5FxdrIgawI5hEvmzK89As2PoiEskXLaLQOUZTLBEWFqUhO3QixqHfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T22:45:38Z"
  mac: ENC[AES256_GCM,data:WzoRVzPnsbOSvOLcDYO3cXW9tqWVqwI8AVNvZ9U9j6qs9FVMqm7RAi+a5j5FpmqBbxsg7djLqYiy3kw3Oo0Pbtn/nvc5I73ODTnfspbySZaUwGuQVcC80Y4o+3Zpa97q6X66cs6N+fkJmm+ETypxVq8SYF3Jjqbl7qDEtdLzLJI=,iv:Hub4h3PmFj6/TdNNhZFBtnAk2hf73VhlX9+MplmPup0=,tag:7AcxSaGKGDLLBdgcKqM0YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-user
stringData:
  username: ENC[AES256_GCM,data:UBvKUyzQ,iv:2QuNmAfVAdOzrjanLPPstrKo1bynxRYngXs++tzKoPs=,tag:ka0s+y0R186rH7KSuXMYmQ==,type:str]
  password: ENC[AES256_GCM,data:bj3948inVlOUUyeF2hCpI+ddI54RxgnV,iv:cRZe9gVV+beQlFRcesU7x6rQxc8bsjqefh8XdJznyUw=,tag:8sgHn2s8+Pb3VQLu7TSRkQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5zaytGRkRnZnpVempE
        aWV1OFNEMlM0RFkram0xK3QrKzI2WUEvbWh3CnZwakF6NDZENTZrVkpIcEM1cEpM
        TUxZMlhyOHdueGZsQW1yRjhHcEd2eE0KLS0tIGlGRlJDNWowZTBTUmpnTHdIK1dq
        M0RNdzRKLzVEZUVWcldPRW11bVo2MHMKoGEjcJNVz1q6mjabJAz8LffoKubQu5m3
        5FxdrIgawI5hEvmzK89As2PoiEskXLaLQOUZTLBEWFqUhO3QixqHfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T22:45:38Z"
  mac: ENC[AES256_GCM,data:WzoRVzPnsbOSvOLcDYO3cXW9tqWVqwI8AVNvZ9U9j6qs9FVMqm7RAi+a5j5FpmqBbxsg7djLqYiy3kw3Oo0Pbtn/nvc5I73ODTnfspbySZaUwGuQVcC80Y4o+3Zpa97q6X66cs6N+fkJmm+ETypxVq8SYF3Jjqbl7qDEtdLzLJI=,iv:Hub4h3PmFj6/TdNNhZFBtnAk2hf73VhlX9+MplmPup0=,tag:7AcxSaGKGDLLBdgcKqM0YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-connection
stringData:
  GOTIFY_DATABASE_CONNECTION: ENC[AES256_GCM,data:6POqZIp36gkHZTmHxqUcoeb5Lvf2/k2TQ5E5pdy16kdfA3bB7Zq7acdazi6LcQ3pjdknIueP8zwDCtkHrQMAOhCeBxrK5XeUqqiWJg8RREO5U7+NJUn55cPIxZC4QLaSYWAMLJ2jXpGu,iv:KwbEqW0Va35tcFmUR2LaI0EdtL4rz1SMK3euLLyytCg=,tag:7mXuILXF8d3ZY4MWR53gUQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5zaytGRkRnZnpVempE
        aWV1OFNEMlM0RFkram0xK3QrKzI2WUEvbWh3CnZwakF6NDZENTZrVkpIcEM1cEpM
        TUxZMlhyOHdueGZsQW1yRjhHcEd2eE0KLS0tIGlGRlJDNWowZTBTUmpnTHdIK1dq
        M0RNdzRKLzVEZUVWcldPRW11bVo2MHMKoGEjcJNVz1q6mjabJAz8LffoKubQu5m3
        5FxdrIgawI5hEvmzK89As2PoiEskXLaLQOUZTLBEWFqUhO3QixqHfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T22:45:38Z"
  mac: ENC[AES256_GCM,data:WzoRVzPnsbOSvOLcDYO3cXW9tqWVqwI8AVNvZ9U9j6qs9FVMqm7RAi+a5j5FpmqBbxsg7djLqYiy3kw3Oo0Pbtn/nvc5I73ODTnfspbySZaUwGuQVcC80Y4o+3Zpa97q6X66cs6N+fkJmm+ETypxVq8SYF3Jjqbl7qDEtdLzLJI=,iv:Hub4h3PmFj6/TdNNhZFBtnAk2hf73VhlX9+MplmPup0=,tag:7AcxSaGKGDLLBdgcKqM0YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-alertmanager-bridge-default-token
stringData:
  GOTIFY_TOKEN: ENC[AES256_GCM,data:pTv8eLPUTfj+5UxVsJkw,iv:bEAiFNCAYye/7cF3v032ZhmHVnVk6KU1PBvSiqA/hVI=,tag:s1WFNss68vEwfgY4Ejg8lw==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5zaytGRkRnZnpVempE
        aWV1OFNEMlM0RFkram0xK3QrKzI2WUEvbWh3CnZwakF6NDZENTZrVkpIcEM1cEpM
        TUxZMlhyOHdueGZsQW1yRjhHcEd2eE0KLS0tIGlGRlJDNWowZTBTUmpnTHdIK1dq
        M0RNdzRKLzVEZUVWcldPRW11bVo2MHMKoGEjcJNVz1q6mjabJAz8LffoKubQu5m3
        5FxdrIgawI5hEvmzK89As2PoiEskXLaLQOUZTLBEWFqUhO3QixqHfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-30T22:45:38Z"
  mac: ENC[AES256_GCM,data:WzoRVzPnsbOSvOLcDYO3cXW9tqWVqwI8AVNvZ9U9j6qs9FVMqm7RAi+a5j5FpmqBbxsg7djLqYiy3kw3Oo0Pbtn/nvc5I73ODTnfspbySZaUwGuQVcC80Y4o+3Zpa97q6X66cs6N+fkJmm+ETypxVq8SYF3Jjqbl7qDEtdLzLJI=,iv:Hub4h3PmFj6/TdNNhZFBtnAk2hf73VhlX9+MplmPup0=,tag:7AcxSaGKGDLLBdgcKqM0YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
