apiVersion: v1
kind: Secret
metadata:
  name: opencloud-collabora-credentials
  namespace: opencloud
stringData:
  username: ENC[AES256_GCM,data:0Wo1Xbo=,iv:czMdHHIcPv1qTfPdV270fh2Jx147xyGn7p1S2ii7chk=,tag:1ID61G8zNbH4PDI7OK3wqg==,type:str]
  password: ENC[AES256_GCM,data:rzfwwlMA2hww1wNr+BFDRWfzk6Q=,iv:UOGMB9Cfzzh2BHKaOTKS4o20dPlzqHzzzY6kRU9oE/M=,tag:SODIOVYxWF3jBfB17S6w+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK2NMSHRJM2NzL0k2L2Np
        V0dLRHp6c0svcU5EVUpyWVRxdTlxcjZPUGgwCmd2ZHVjYUVOZXBEWlJKRnRkaUZa
        MDJUU2hOZURrSVBuMWtkbzJBK3QxSUkKLS0tIHl1Y1hyNWJXWUdHN0poc0tDWnhL
        MjVOL21DZW5sVVhsWFpaRFk3UDkrT0kKxAigw/iy86qUQoJcvckOAoYgrRT41oLq
        9lPMWcw3ZCxO99BdWuknAauJeo3c+AFnDzWxq8ZI3WnjiBZM+3L2QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T00:27:26Z"
  mac: ENC[AES256_GCM,data:5CWRZ+Hrrl/qLX82/qxw1tkZjB5YQChsKvUJh72MeZeit7n9VuzZ0BvsN+YiCFh+cOyDaw9fewv0SYXCz6QonDDdEttGrefUV/aNw0YohfTrdsoZYPK1M2pTJ9csN8TR5WA9h9o+rCQXzp4tpX7HiM4/GcqZScC1DNBXk9QZrsw=,iv:2b4+o0swR5zYHEjQHk6mTAFnVklfPeYaEY4Hc/lVxIA=,tag:h9UUVIJ8Qwn/MYGE3Njk7g==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-s3
  namespace: opencloud
stringData:
  accessKey: ENC[AES256_GCM,data:N9h1fZy/2Tjt4dMoFk/sXI1QHkJAEyNQAp0=,iv:ea4ue1tAxZTnBXaoAg82n3f7FL259/Nckre7kr8nfSc=,tag:JGpjgBfRrpCiszc7w3vNfQ==,type:str]
  secretKey: ENC[AES256_GCM,data:NHt6+McW43mwBP8WB/G+ydym3boBp3sbqMxXmxe72MHNjYh26uGBfV3RGI0KUrCOuCKxVL/4F5u8Tm9kgyPEew==,iv:UE4Ug1MmRVglnRh5pFbmSRfK+Jq08Tdo0P2xdZTtrqw=,tag:koypEMJLyFec/VaGy0hYVQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK2NMSHRJM2NzL0k2L2Np
        V0dLRHp6c0svcU5EVUpyWVRxdTlxcjZPUGgwCmd2ZHVjYUVOZXBEWlJKRnRkaUZa
        MDJUU2hOZURrSVBuMWtkbzJBK3QxSUkKLS0tIHl1Y1hyNWJXWUdHN0poc0tDWnhL
        MjVOL21DZW5sVVhsWFpaRFk3UDkrT0kKxAigw/iy86qUQoJcvckOAoYgrRT41oLq
        9lPMWcw3ZCxO99BdWuknAauJeo3c+AFnDzWxq8ZI3WnjiBZM+3L2QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T00:27:26Z"
  mac: ENC[AES256_GCM,data:5CWRZ+Hrrl/qLX82/qxw1tkZjB5YQChsKvUJh72MeZeit7n9VuzZ0BvsN+YiCFh+cOyDaw9fewv0SYXCz6QonDDdEttGrefUV/aNw0YohfTrdsoZYPK1M2pTJ9csN8TR5WA9h9o+rCQXzp4tpX7HiM4/GcqZScC1DNBXk9QZrsw=,iv:2b4+o0swR5zYHEjQHk6mTAFnVklfPeYaEY4Hc/lVxIA=,tag:h9UUVIJ8Qwn/MYGE3Njk7g==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-admin
  namespace: opencloud
type: Opaque
stringData:
  adminPassword: ENC[AES256_GCM,data:ZnT+lcGb+YA2yxWCvWSZPoU4HWPa7I9lkE+alStio6g=,iv:unbSYylPHJ+zNmVuZaQTpJWKqgtDYFp9ZgNy24yThOo=,tag:Mv2gOHdI4JlUdDrOL3pT4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK2NMSHRJM2NzL0k2L2Np
        V0dLRHp6c0svcU5EVUpyWVRxdTlxcjZPUGgwCmd2ZHVjYUVOZXBEWlJKRnRkaUZa
        MDJUU2hOZURrSVBuMWtkbzJBK3QxSUkKLS0tIHl1Y1hyNWJXWUdHN0poc0tDWnhL
        MjVOL21DZW5sVVhsWFpaRFk3UDkrT0kKxAigw/iy86qUQoJcvckOAoYgrRT41oLq
        9lPMWcw3ZCxO99BdWuknAauJeo3c+AFnDzWxq8ZI3WnjiBZM+3L2QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T00:27:26Z"
  mac: ENC[AES256_GCM,data:5CWRZ+Hrrl/qLX82/qxw1tkZjB5YQChsKvUJh72MeZeit7n9VuzZ0BvsN+YiCFh+cOyDaw9fewv0SYXCz6QonDDdEttGrefUV/aNw0YohfTrdsoZYPK1M2pTJ9csN8TR5WA9h9o+rCQXzp4tpX7HiM4/GcqZScC1DNBXk9QZrsw=,iv:2b4+o0swR5zYHEjQHk6mTAFnVklfPeYaEY4Hc/lVxIA=,tag:h9UUVIJ8Qwn/MYGE3Njk7g==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: opencloud-init
  namespace: opencloud
type: Opaque
stringData:
  jwtSecret: ENC[AES256_GCM,data:e9oqadP1JHzUQxsYlkK0GFcZJHN5bL26LEVrV8EpEzs=,iv:FxoQcvDZ/wxy/RuxlxkjrTjrV9x4J15f1gYNuZNawTM=,tag:hEzvB4bSD3dO/r6fmmSf8Q==,type:str]
  machineAuthApiKey: ENC[AES256_GCM,data:p2l3JIDd++6t1D/2QpRgLfYKWCR+Btq5No0aCQM08oA=,iv:NPjpDzQcbthlWjMxRYHZToLQzLR8DosNxLr457M5b/k=,tag:iVGElsPcGRLqNaa6xEhrxw==,type:str]
  transferSecret: ENC[AES256_GCM,data:s+a2LCHQt0kmq+4QWc7AweDGzEHtnuuzJoIRRpO2pn8=,iv:hCHMrIQoGWHh929ZvaUcIXKLRzGZsVjGzqx4Pois2xQ=,tag:R0VBZ1mDlknrNQwlvo3lhg==,type:str]
  serviceAccountSecret: ENC[AES256_GCM,data:mxfo9FbnSQf6pYB6fE32xoGuvg/XIvW4d1EgJahysEo=,iv:+qh9PCkUNpn60PuqaX+c1XNWAVH2iWcMwux8N8jkf4I=,tag:Pzkf7GYeTuzNUhMhbgY4uw==,type:str]
  idmServicePassword: ENC[AES256_GCM,data:GJxLPcFS6wLgiIMTMKomlVQAskAAgPUo86SsqT3Dldc=,iv:wlcZ5YhzCljT2qYclFnS4l5KClC9jQwAYqwPp97vndo=,tag:6q5P4xLMBF/YVqGowD8miQ==,type:str]
  idmRevaServicePassword: ENC[AES256_GCM,data:tM9wx0w0v8lgpKAFjl79d0wn7uCCKMUARrsVxQt8API=,iv:NfJ+qvTopFnub0z6XNnmQ2mEe3HIWYrv0TT55TcTkT8=,tag:QKYjIxUP1QIN2dlf1/ZMzA==,type:str]
  idmIdpServicePassword: ENC[AES256_GCM,data:uwUAcMMfT0Ph5a/yxRlz3o14H7L5eknvYqgw08IqIoM=,iv:oKjbhB+dUsG6yRKfGeg0IC11+CT+Gtr2MbPTcIu2BdE=,tag:h90/59rr7eB+OOW2t7jXUQ==,type:str]
  collaborationWopiSecret: ENC[AES256_GCM,data:c+4SnAkbCm7d7rR/ftMSx0D2MUufBvX6228hOZwJan0=,iv:eMWbx6GqXyOxNRU3juq8P9AWwVSSam+2jBTplKCHkuM=,tag:tf20Yv/RUHuY+bWgxQ0PgA==,type:str]
  systemUserApiKey: ENC[AES256_GCM,data:9dbhuewgaOqo98gTMvgFM+o1P+uG0Cz7yWPAaTBighI=,iv:+805kQ+7pBXMopagICH1xPs9EX41vRT57lNk3u616n0=,tag:ln/O9EkNekveyV87Wn+bYQ==,type:str]
  urlSigningSecret: ENC[AES256_GCM,data:d8gZN2k2A2gB5CPRIMTvfhpTmagr3PBI4CU4UJQ5ENY=,iv:WL+SzH4+8VRb1U+Sde7BK/rnxup4NwPevek1nG/K8S4=,tag:kYwIc+0MriZXXbbBF9982w==,type:str]
  thumbnailsTransferSecret: ENC[AES256_GCM,data:OoyrlaKKf/03DyE1PW8gVFUqDKkafFLhdg8HSc5q4Nc=,iv:4NrIw5H+3Q3vQ29g+QXLYMFMwHgbmGcnRbioXSo4ORo=,tag:aNiOv9P3+CJ1HFAV8ULSlA==,type:str]
  systemUserID: ENC[AES256_GCM,data:lJbclLlzZpzOPe+2QWymJcbPXdskfvAWtz5cuBNspfsniFqW,iv:gp4XoboKqoBZQ+TLbqp/j6Hysgr681EobnZmbDKm2U4=,tag:9SSmXuuRQnKJChzJDX7GKg==,type:str]
  adminUserID: ENC[AES256_GCM,data:enT+N644B7wXrQc2E5MAG9eHL9HB+OWxmOAZzb0jB0zctm8c,iv:NZmhDu7GEHctZCmmQ4JRObZ0N9/QVkwGAnP/NtS8woI=,tag:GwIEB0o6ya0DS6H4WR41wA==,type:str]
  serviceAccountID: ENC[AES256_GCM,data:GCE8+aQ576kRo1X1jyLfytCpjbx8kAp6y1Zxud1Q+0GA6Qhw,iv:yCgXACSa4zivDmxLU+00gCYA727xpqbBMOhUZEg9/2Y=,tag:PpqEHRQWtl5wseKxGhKyWA==,type:str]
  graphApplicationID: ENC[AES256_GCM,data:FFbiPmMRTvxhoRcKy14FU8YNhOwD3cVIksTw2KQVymPxOivF,iv:7MKkAygyfbwN2qI/cEXwIcbpPeNqRBeX911ZS2Llg7U=,tag:l5QLl1I6We861musl05nEw==,type:str]
  storageUsersMountID: ENC[AES256_GCM,data:Ztl7jUBrEXOu1a5rbf1jR7sW3cyKDvgEdiEeWxNWByUEmQ1O,iv:rDKhcoaFQXN09yMOtoG90X3ou4zdIRdBBcZzz43il0g=,tag:pVsl1XC1t2ZbY9rtzEqvAw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZK2NMSHRJM2NzL0k2L2Np
        V0dLRHp6c0svcU5EVUpyWVRxdTlxcjZPUGgwCmd2ZHVjYUVOZXBEWlJKRnRkaUZa
        MDJUU2hOZURrSVBuMWtkbzJBK3QxSUkKLS0tIHl1Y1hyNWJXWUdHN0poc0tDWnhL
        MjVOL21DZW5sVVhsWFpaRFk3UDkrT0kKxAigw/iy86qUQoJcvckOAoYgrRT41oLq
        9lPMWcw3ZCxO99BdWuknAauJeo3c+AFnDzWxq8ZI3WnjiBZM+3L2QA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T00:27:26Z"
  mac: ENC[AES256_GCM,data:5CWRZ+Hrrl/qLX82/qxw1tkZjB5YQChsKvUJh72MeZeit7n9VuzZ0BvsN+YiCFh+cOyDaw9fewv0SYXCz6QonDDdEttGrefUV/aNw0YohfTrdsoZYPK1M2pTJ9csN8TR5WA9h9o+rCQXzp4tpX7HiM4/GcqZScC1DNBXk9QZrsw=,iv:2b4+o0swR5zYHEjQHk6mTAFnVklfPeYaEY4Hc/lVxIA=,tag:h9UUVIJ8Qwn/MYGE3Njk7g==,type:str]
  version: 3.13.3
