apiVersion: v1
kind: Secret
metadata:
  name: opencloud-ldap-bind
  namespace: opencloud
stringData:
  reva-ldap-bind-password: ENC[AES256_GCM,data:YUYBtS5ox8PWh4oaSJIZplPm4wQIXZzbIkh8FnI=,iv:LrcXkDXHwwSryHxGtknmqs5Gvds4Qa9PehYLFLWoS1A=,tag:F6OUabOQk+LxphlGCsywVQ==,type:str]
  graph-ldap-bind-password: ENC[AES256_GCM,data:rXOxrbAuHcC7Z8XoWTyYwFNcYk/35ExlYP32RHw=,iv:/3IIEgkDVkxXBB1g0vtO9QJyVaml6BI82VCi7eLxJi4=,tag:+9CQ9fq1RezF33bCxR8Esw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCejJDcEw3TTU5c0JZdHRI
        dG9YbHp2K3F5SjltNG9Udi8zR0t5dGl0WFRFCjRwNDZqN2MzcUtySjl0aGdXWmpF
        Wm12dXk1ZHZ6bVRRSGVueGVmcklGeEUKLS0tICsvZmVRRUNJWFlpaEdUUC9OQ0c1
        TEhBNU03VUFudGxLckwwbE44UEtTLzQKfUylDt2oIGw7D8CqfAaBsk9nH/q2D9qq
        PrDL0bldGuicvdzF+0puTUrBGNXzAZmILT/KHsKMqAxOuTTLXYFrpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T12:45:20Z"
  mac: ENC[AES256_GCM,data:B54MTpYugeQ3LigCkq9Fd9sFkJBqs6YMEzZQNnHnlt9tYCKZB4l6DS89zLn8Z0SG5hGNQFaYs0BPjDotpAdBWy5yS3xWWg1gwiLI+7pyUv27CVFTKHgZuesWeVJAHMXGa/5YfPoAJsC99/Ra2kCTIeQTV1OTLXZ1SclHGE+B42s=,iv:17zFrwbQQ+HajlQfZvinCgbwgTk3CZN9QjgEC+RiUaQ=,tag:TEWlK0RPwT8w6/WYAh48aw==,type:str]
  version: 3.13.3
