apiVersion: v1
kind: Secret
metadata:
  name: opencloud-ldap-bind
  namespace: opencloud
stringData:
  reva-ldap-bind-password: ENC[AES256_GCM,data:DMWnjyjwUhCp9HF6Zvj26sFHszfht2I9FUK/oZDZ2ruCYzkGd4rnz/2w5KJYNpFmRQgtHCv9V0SGiN4sZXMUvJK4NqRv2EFQesDau94kcbJZ5P8Vd+9vh2hxgkvJFmQXhHXZqVuzp/pEw8OO9gOt5RMzN5KD+N/LLgbGqSwus1OKWZjlBkb8sb9ewpb2h/PJJDpYT0OTrQAR2mo5kODowg+ADh2hGvSksKwcrqHqSMvsEitq1AXIWWrPphkX93Ps/Dg7WRAA90dgBcVRrhXKsNrfagHNVH1PCJZPTQxtkeILAyColEGoudSxdKtE5H7PGIE1oAUqJ2bxlVd3vyKcVCimpVh6YhCpYD/0kMEPvTDpeLCkn2ivErUG4cndrKTtKWTpF0AxWamPTDspwBcj1xE+h/LwqWXygc1I4BQ1h/DHI/HFy8+EgpA3SWXUgnY9kZJ2PRBb9Q==,iv:1bEkRpXZIMYiq9YcL/dELpCijdeZx/nvADD1q5U3s3I=,tag:fx53CMup33/ydCAwhGO+BQ==,type:str]
  graph-ldap-bind-password: ENC[AES256_GCM,data:cpbuwIzFt7CWVzRw/sQ49IRmJYCn/8c3BYqRPSXa/0MoeSK4NMKcx/Q6gGe3yhGXrgbaopjWiw9rwykznZduIPmrafh818mr3O6h81wqkpCxy68gnTD7ci6TdhbdNq7U7D6derG/PeyhgRQYveuZl6PINiZeDUvHR2GRBgv5fUXsTU5u937bMT3xe7q+MkT8k6VMecHaGNGKugQ+Olk6iEzuLZ5yWMzh8dc2JcmgIqFl3Wvg7+ahDY2iaT4JfbO6laIlchIZWhhclvcRXgIz0EYeZZeAXHGsQsk9hWLO5Kqf/xrkp/esXgofOz69rQk8cuTwqj1GpuxX6M/UNQQ0XUocp3NjAV3Vou4TqxW5W0qD0icsM+mcgidy1oyXgZH12yAs8gRU0x3a00f+aFwmY51G2e5DYO355C/ZkNXq6duF5F5OA97pxPS606I/ebCJkv+r3MfAcw==,iv:PqX27jQF1PejL6dw19UkzcY6XraVS0nY3zAzBxUYO/c=,tag:2WVz5aK6LLUva5LWCZ+FfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCejJDcEw3TTU5c0JZdHRI
        dG9YbHp2K3F5SjltNG9Udi8zR0t5dGl0WFRFCjRwNDZqN2MzcUtySjl0aGdXWmpF
        Wm12dXk1ZHZ6bVRRSGVueGVmcklGeEUKLS0tICsvZmVRRUNJWFlpaEdUUC9OQ0c1
        TEhBNU03VUFudGxLckwwbE44UEtTLzQKfUylDt2oIGw7D8CqfAaBsk9nH/q2D9qq
        PrDL0bldGuicvdzF+0puTUrBGNXzAZmILT/KHsKMqAxOuTTLXYFrpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:48:15Z"
  mac: ENC[AES256_GCM,data:dflasQhNvAk+/M/0bYKvchQhz/kBrd3GiC//vOKjF0J5EnUnVajCfN9mOQqNkmg3GEv7bCaRcXQP0ZX2MdPw8woHD4KzubOgWVcbM5JY93c23OLTMWswrEdKM2kYeL2Sm41nEeX/s9UjM3o+wlMjykkjdzvO4N6MrTGK+RDjJR0=,iv:e1sVaRk1Ykme1zQp9JmRkibw0H86MaS03vM6mJGqmMg=,tag:2QuKJ0pJHbxhrRs28VUE7g==,type:str]
  version: 3.13.3
