apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-restic-config
  namespace: qbittorrent
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xSShw1wjQtry196z2c9IS1TqJwzZlW+TKPUc3A==,iv:aq0IxDI9CZwHvTSo6rQHnpzWWpinumC1E55anpEuFyI=,tag:2sjJtZhCi9GAopevHKsYWw==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lKv8m1hX5BL/m8EGCXyjpPqPfVU3UAIRsZLdh6rynJAMN3gpnCPPOq0Ym5Y0uR3sK9oOL1s=,iv:ieH4c19YAYKhtD6Sb7YbSmhJBbyMO/JJi2h1o5XFc8A=,tag:x/BdF2L06uHwmQ0dcDNMeA==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:7fFWmS9ameja/EyVtVaIr5Rw+F0=,iv:RDmhw/G6J5pMjnQHC8CahebSbKtZ9b/mlwAlntPz76U=,tag:SlYMTCK6juh/zcKznN83BA==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:PJiQ2y/kRAsnXpM7ZQGudbuWUamIL+ADSwkisqhqHG95wRvxC8/rB4jcy1/Y8xviakYv5ZjJ96dCqxTNBApf+eZL,iv:NyMCF72DBw83qGQwV2BNUgoo6oahoSuEUzWSPxwfTqY=,tag:c15J8br4PzrXSCwaDr/svg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYUdCdVhDN1EwdjRCbWh0
        c0RVcmFkM0JOdVRITytjQzZmVDQxZFVvNGg0CkVBMm5yWDVaWkpRc3Vpb0ZMRHdT
        WEg2SVRMWHl0V2ZjK2VvU2J6MjVCekEKLS0tIDRDQ1RleC9lYzRuaDRySkdxeDRX
        U0hWYVpsUFd4UFIrN2pQVEd1UzFjR2sKCrtz/r1aPKIlnHRinrYQnBLafVKnkK8C
        r4G7wIlHj6K2A/xPvjFOQE56xdJ8ran6vJ45vfuo5/s4oL0asiw6fA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:20:09Z"
  mac: ENC[AES256_GCM,data:o11AMZI+DtXoB2gJrzc8cDDzBAAuCIZunHTCNHz3tPKfZjFKxsU/2ixxJPD950pJYA/MritJ5du5ZJehjviX47HU00eDF1B4HgbNzMass2Ax3A3ge5j8KicrgVLreTo6J49RPN8hVpy47fUupKMC76nw1O2L/unDNBxALfLpf3U=,iv:twkLihLjbUwEmG6hdTXmrxE22RvIY9YsngM2mX8Ylr8=,tag:eLtke8yiJTuUpsXdAqcZfA==,type:str]
  version: 3.13.3
