apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-credentials
  namespace: nextcloud
type: Opaque
stringData:
  nextcloud-username: ENC[AES256_GCM,data:bDcCCbU=,iv:SY7+VTx2HkTiZ76WHYdjSOvtq3cTPNQeNsMXbB4pwGg=,tag:7iBx+77PTqqpdoQCFOAC8g==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:MdjAGkHxJIbPBToQDzOO8DWFyhQ=,iv:C1z634NWmtxBFfw+s8svseaxm8naaiYfKz8EtiEQqeA=,tag:u0joevflBkLyiZ1Kzun0hw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeWRrREtTY3lmVkt5dGpU
        dmRxZkJ1MHZEekEvd2tWQnpXMGdpekhvRkZJCnNWQ0srbklweldRcEVaY2JVQnVv
        S0xHM20wR0tSWFVLb0hEVlRDWHV1RkkKLS0tIG1Ielh6d0RxT3ZRVEM2bkVrZ0U5
        Uk1naFF5YXQ1S2poVmdBbldyYThDelkKtqFoEm+TX64E1kkBhMRMdahBAIzb+ATg
        VybnKGQN1giPP9JpNsawHzHYQmg41T3ZaoqTN+pR9XI8t6XNrHlfMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T09:25:00Z"
  mac: ENC[AES256_GCM,data:rfIMrmgJCtp0YvkPJ//xzUOIiafuoGdFjeH2pdsV0GgSQQrcO5uwDxsgBw5+8mGUDRjUtHaW9OVBzpL8yhyZhfDD8PXD1PS8gXquLr7auLmhJxE32Dko/km7w7qh+mhYxntM8qQ48vIMLc6fdm7Hmoon6q24n40+S3vuSbYZBBI=,iv:ZowWnysKYpVFuY1uNLN0nQEmdtqFMIHMSbr/bbipIVY=,tag:uQC1emnSiW1B2e6ewC8/6Q==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-s3
  namespace: nextcloud
type: Opaque
stringData:
  host: ENC[AES256_GCM,data:tafBR8nKwwh5rBElDtao0DYBsJrgY2VpV8gvt33rCg==,iv:R4riOLAx8vCCOxhB3Wx2KsI6h+bwSgu0j0gH2id+BO4=,tag:rAi+GRUlVYs1T5HEARwg1Q==,type:str]
  accessKey: ENC[AES256_GCM,data:kEH9ZQXIjTJA0Hz3rPpob3+7plc0CWNAkAs=,iv:DRSvgvZTVC7S6hW+Jlp850ZFZZRFkUryq+3jjnUa78Y=,tag:x+VBX2YnuCTkOoLQHxcDDA==,type:str]
  secretKey: ENC[AES256_GCM,data:h0eU6uyrbWEK/IAysTzCoNgDMJO+ZI9/dzA25dHugWZmfdioMuD/aXVa3bdBup7hz0qmXMdcRUr8bf2sA68Q7g==,iv:9WrNED2omMo4QlDOEjrJoXAxE6p8i8PjM54VBJhtoqQ=,tag:a3wKMLhZlLKLcQDFrUTbHQ==,type:str]
  bucket: ENC[AES256_GCM,data:QpUPFHCJShJq,iv:vu35CwsjDirpvVxM5l/t4MwVR7TdEAaFZnHI2EiU+xs=,tag:fEWU/m2nR2I8ag+76F2QAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeWRrREtTY3lmVkt5dGpU
        dmRxZkJ1MHZEekEvd2tWQnpXMGdpekhvRkZJCnNWQ0srbklweldRcEVaY2JVQnVv
        S0xHM20wR0tSWFVLb0hEVlRDWHV1RkkKLS0tIG1Ielh6d0RxT3ZRVEM2bkVrZ0U5
        Uk1naFF5YXQ1S2poVmdBbldyYThDelkKtqFoEm+TX64E1kkBhMRMdahBAIzb+ATg
        VybnKGQN1giPP9JpNsawHzHYQmg41T3ZaoqTN+pR9XI8t6XNrHlfMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T09:25:00Z"
  mac: ENC[AES256_GCM,data:rfIMrmgJCtp0YvkPJ//xzUOIiafuoGdFjeH2pdsV0GgSQQrcO5uwDxsgBw5+8mGUDRjUtHaW9OVBzpL8yhyZhfDD8PXD1PS8gXquLr7auLmhJxE32Dko/km7w7qh+mhYxntM8qQ48vIMLc6fdm7Hmoon6q24n40+S3vuSbYZBBI=,iv:ZowWnysKYpVFuY1uNLN0nQEmdtqFMIHMSbr/bbipIVY=,tag:uQC1emnSiW1B2e6ewC8/6Q==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-collabora-credentials
  namespace: nextcloud
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:7kkuoRI=,iv:2bBD7fbHwGkC+mURBOhFZ42My1CkJjhLa0ZzdqV2S+c=,tag:eyYehKt1q1ycLw6k1Tm+gQ==,type:str]
  password: ENC[AES256_GCM,data:/s+fX0DqwCQY7ugo+wxi7beT9c4=,iv:Xabok+MElGskv2K6RymoUN00wGY/H5jPhpH0gObOPvE=,tag:k/5HEZIUFZvm/ouRUj316g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeWRrREtTY3lmVkt5dGpU
        dmRxZkJ1MHZEekEvd2tWQnpXMGdpekhvRkZJCnNWQ0srbklweldRcEVaY2JVQnVv
        S0xHM20wR0tSWFVLb0hEVlRDWHV1RkkKLS0tIG1Ielh6d0RxT3ZRVEM2bkVrZ0U5
        Uk1naFF5YXQ1S2poVmdBbldyYThDelkKtqFoEm+TX64E1kkBhMRMdahBAIzb+ATg
        VybnKGQN1giPP9JpNsawHzHYQmg41T3ZaoqTN+pR9XI8t6XNrHlfMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T09:25:00Z"
  mac: ENC[AES256_GCM,data:rfIMrmgJCtp0YvkPJ//xzUOIiafuoGdFjeH2pdsV0GgSQQrcO5uwDxsgBw5+8mGUDRjUtHaW9OVBzpL8yhyZhfDD8PXD1PS8gXquLr7auLmhJxE32Dko/km7w7qh+mhYxntM8qQ48vIMLc6fdm7Hmoon6q24n40+S3vuSbYZBBI=,iv:ZowWnysKYpVFuY1uNLN0nQEmdtqFMIHMSbr/bbipIVY=,tag:uQC1emnSiW1B2e6ewC8/6Q==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-redis-credentials
  namespace: nextcloud
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:ee7q3p+ZYICn67+SFkywfYg9mhP8ryq5akeV8w==,iv:yqEk1rWocssO8To9bkRaMPPZhWyBwzoxoT2KZr2iyJM=,tag:2W+H384fjsov3ZGK4VnBUw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeWRrREtTY3lmVkt5dGpU
        dmRxZkJ1MHZEekEvd2tWQnpXMGdpekhvRkZJCnNWQ0srbklweldRcEVaY2JVQnVv
        S0xHM20wR0tSWFVLb0hEVlRDWHV1RkkKLS0tIG1Ielh6d0RxT3ZRVEM2bkVrZ0U5
        Uk1naFF5YXQ1S2poVmdBbldyYThDelkKtqFoEm+TX64E1kkBhMRMdahBAIzb+ATg
        VybnKGQN1giPP9JpNsawHzHYQmg41T3ZaoqTN+pR9XI8t6XNrHlfMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T09:25:00Z"
  mac: ENC[AES256_GCM,data:rfIMrmgJCtp0YvkPJ//xzUOIiafuoGdFjeH2pdsV0GgSQQrcO5uwDxsgBw5+8mGUDRjUtHaW9OVBzpL8yhyZhfDD8PXD1PS8gXquLr7auLmhJxE32Dko/km7w7qh+mhYxntM8qQ48vIMLc6fdm7Hmoon6q24n40+S3vuSbYZBBI=,iv:ZowWnysKYpVFuY1uNLN0nQEmdtqFMIHMSbr/bbipIVY=,tag:uQC1emnSiW1B2e6ewC8/6Q==,type:str]
  version: 3.13.3
