---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certs/selfsigned-issuer.yaml
  - certs/root-ca-certificate.yaml
  - certs/root-ca-issuer.yaml
  - certs/intermediate-ca-certificate.yaml
  - certs/intermediate-ca-cluster-issuer.yaml
  - certs/ca-bundle.yaml
  - certs/cloudflare-secret.sops.yaml
  - certs/cloudflare-cluster-issuer.yaml
  - certs/cloudflare-certificate.yaml
  - metallb/ip-address-pool.yaml
  - metallb/l2-advertisement.yaml
  - longhorn/storage-class.yaml
  - longhorn/volume-snapshot-class.yaml
