apiVersion: v1
kind: Secret
metadata:
  name: backup-s3-credentials
  namespace: servarr
stringData:
  accessKey: ENC[AES256_GCM,data:Zyx3pmnrZJJTYPRSSQhGpAvdwb/Ko6oSmj5fpg==,iv:XdtjddG0iJpF38ZRsSk9Ma/6o2lzsuIsxtSmzstoz5U=,tag:05GKkKvb6gplzOVCH8Rwvg==,type:str]
  secretKey: ENC[AES256_GCM,data:R8RYcX9bwwq1xlK9WYG7bcjRnPLzt/4BEQAiUCDFJT33gVKyhuYSYgKxXZBjjECB0JJ5fDE=,iv:wzJHojc0Y1cKi7Fv7Rj5p+OUKeYvryWE8qdFgCKvc7M=,tag:KLal82wz+tMkThcNeGPsoA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGV1bEZtWkVBcnhhSjlJ
        MG9UOFBPVWt5dWpoNlFWbkp4RUF5c3Z0bGlVCk5QZjlTd1Zxd0RtaWJoWnplelg4
        dUZPMTZKTFpOVkwyY1ZTODRGY3hMU2sKLS0tIHR4cm9GQU1veW9SQmljZG1JRUU2
        QjB5SXlYVFBiNXc3YXBDWkxFV1FERXMKRXE64akROnHJjGb50Ib8nNKaVnsyq5IE
        FNfOMwznnYDMRBhdLwbm1YHZwTgfQkv5cl4sWYFv/RAeKm4/Z/PbeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:53Z"
  mac: ENC[AES256_GCM,data:Qgw9AYtVbYcd5VP+kphYvSDba7OnmvH53qmxbKXdYibJP5YuRj3rDrirdzeopeXnVDynw6h5iidzQJxBiy/oX6BBkiDu70Ym0aWeAMtcQySoHvJDKljjceG1WdN0YV+hHkUwcbkIdefAPBNY89oJ60STI0lhBs3VDZPX2C4DnTg=,iv:kP4i8pRHpnkrruKEZpsourkEHSkkAnbIe0cJ+I8GLTI=,tag:yKEV58tBrF4hmDGbjreUig==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: servarr-cnpg-user
  namespace: servarr
stringData:
  username: ENC[AES256_GCM,data:pGkKYecPog==,iv:tXRvYm1hpnFMoHu1z5ZIuiufSYqkHiXFnFKB+vBk4gg=,tag:hDONK1dueAB/AhlbuTK1UA==,type:str]
  password: ENC[AES256_GCM,data:N62SofSLNbLVwjiUEZ9xeaSfOJD62+CcAAUInUj179k=,iv:xrwIVze4Vg8opFQqb/yXcB0z7PhwOYsa3IDeQlh0h4Q=,tag:iYKwL5gKHUstlV7XaFZc/g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGV1bEZtWkVBcnhhSjlJ
        MG9UOFBPVWt5dWpoNlFWbkp4RUF5c3Z0bGlVCk5QZjlTd1Zxd0RtaWJoWnplelg4
        dUZPMTZKTFpOVkwyY1ZTODRGY3hMU2sKLS0tIHR4cm9GQU1veW9SQmljZG1JRUU2
        QjB5SXlYVFBiNXc3YXBDWkxFV1FERXMKRXE64akROnHJjGb50Ib8nNKaVnsyq5IE
        FNfOMwznnYDMRBhdLwbm1YHZwTgfQkv5cl4sWYFv/RAeKm4/Z/PbeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:53Z"
  mac: ENC[AES256_GCM,data:Qgw9AYtVbYcd5VP+kphYvSDba7OnmvH53qmxbKXdYibJP5YuRj3rDrirdzeopeXnVDynw6h5iidzQJxBiy/oX6BBkiDu70Ym0aWeAMtcQySoHvJDKljjceG1WdN0YV+hHkUwcbkIdefAPBNY89oJ60STI0lhBs3VDZPX2C4DnTg=,iv:kP4i8pRHpnkrruKEZpsourkEHSkkAnbIe0cJ+I8GLTI=,tag:yKEV58tBrF4hmDGbjreUig==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-cnpg-user
  namespace: servarr
stringData:
  username: ENC[AES256_GCM,data:vT23o9GJYLA=,iv:2ZnKmLBA90/rxWAW+9ZRPTDNT0GQuSoVCHPJ7LC/hbg=,tag:3KQBgE+E95PXMwHCKPE0Fg==,type:str]
  password: ENC[AES256_GCM,data:zfyVp+KsoQRNtyNowEi7,iv:YnzcVT/72r2hfAkCovuCgEaR+/mYn69nKIeQIps1xC8=,tag:vmsYIyKPSEmQrpEB4lbsbA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGV1bEZtWkVBcnhhSjlJ
        MG9UOFBPVWt5dWpoNlFWbkp4RUF5c3Z0bGlVCk5QZjlTd1Zxd0RtaWJoWnplelg4
        dUZPMTZKTFpOVkwyY1ZTODRGY3hMU2sKLS0tIHR4cm9GQU1veW9SQmljZG1JRUU2
        QjB5SXlYVFBiNXc3YXBDWkxFV1FERXMKRXE64akROnHJjGb50Ib8nNKaVnsyq5IE
        FNfOMwznnYDMRBhdLwbm1YHZwTgfQkv5cl4sWYFv/RAeKm4/Z/PbeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:53Z"
  mac: ENC[AES256_GCM,data:Qgw9AYtVbYcd5VP+kphYvSDba7OnmvH53qmxbKXdYibJP5YuRj3rDrirdzeopeXnVDynw6h5iidzQJxBiy/oX6BBkiDu70Ym0aWeAMtcQySoHvJDKljjceG1WdN0YV+hHkUwcbkIdefAPBNY89oJ60STI0lhBs3VDZPX2C4DnTg=,iv:kP4i8pRHpnkrruKEZpsourkEHSkkAnbIe0cJ+I8GLTI=,tag:yKEV58tBrF4hmDGbjreUig==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-standard-cnpg-user
  namespace: servarr
stringData:
  username: ENC[AES256_GCM,data:6jnxRajj4zSQT1V0ryn2,iv:9+/H9N8SakePGarBXufz/bubav/VY1DQBiCnh9ZWUwM=,tag:iGMowG725Ftzrne1H7ZOoA==,type:str]
  password: ENC[AES256_GCM,data:bn+BZytDPDHWNwDqJ3Fw,iv:SiRmSSdZKL9haXqLEZg1/Kw1f0vJitno2BbOW2Q33Ew=,tag:Y9RuEB9pEmOh3VMMSV31vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGV1bEZtWkVBcnhhSjlJ
        MG9UOFBPVWt5dWpoNlFWbkp4RUF5c3Z0bGlVCk5QZjlTd1Zxd0RtaWJoWnplelg4
        dUZPMTZKTFpOVkwyY1ZTODRGY3hMU2sKLS0tIHR4cm9GQU1veW9SQmljZG1JRUU2
        QjB5SXlYVFBiNXc3YXBDWkxFV1FERXMKRXE64akROnHJjGb50Ib8nNKaVnsyq5IE
        FNfOMwznnYDMRBhdLwbm1YHZwTgfQkv5cl4sWYFv/RAeKm4/Z/PbeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:53Z"
  mac: ENC[AES256_GCM,data:Qgw9AYtVbYcd5VP+kphYvSDba7OnmvH53qmxbKXdYibJP5YuRj3rDrirdzeopeXnVDynw6h5iidzQJxBiy/oX6BBkiDu70Ym0aWeAMtcQySoHvJDKljjceG1WdN0YV+hHkUwcbkIdefAPBNY89oJ60STI0lhBs3VDZPX2C4DnTg=,iv:kP4i8pRHpnkrruKEZpsourkEHSkkAnbIe0cJ+I8GLTI=,tag:yKEV58tBrF4hmDGbjreUig==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-anime-cnpg-user
  namespace: servarr
stringData:
  username: ENC[AES256_GCM,data:rZ8gsMPli4Oy8Q0t,iv:oC07cwlGZgOfbgqyuXUnS7D9lyiLBSJW0/vnCBhpj5g=,tag:IQSVy4SGJNP60bsXM6sV8A==,type:str]
  password: ENC[AES256_GCM,data:0W0ZJai/eJhv6eDARKZF,iv:nPwahY3bo1cm67MTicijqTH8RfhhODYYKfHwcrod9wE=,tag:N9n6VfO1va4z9atWHNQmTA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGV1bEZtWkVBcnhhSjlJ
        MG9UOFBPVWt5dWpoNlFWbkp4RUF5c3Z0bGlVCk5QZjlTd1Zxd0RtaWJoWnplelg4
        dUZPMTZKTFpOVkwyY1ZTODRGY3hMU2sKLS0tIHR4cm9GQU1veW9SQmljZG1JRUU2
        QjB5SXlYVFBiNXc3YXBDWkxFV1FERXMKRXE64akROnHJjGb50Ib8nNKaVnsyq5IE
        FNfOMwznnYDMRBhdLwbm1YHZwTgfQkv5cl4sWYFv/RAeKm4/Z/PbeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:53Z"
  mac: ENC[AES256_GCM,data:Qgw9AYtVbYcd5VP+kphYvSDba7OnmvH53qmxbKXdYibJP5YuRj3rDrirdzeopeXnVDynw6h5iidzQJxBiy/oX6BBkiDu70Ym0aWeAMtcQySoHvJDKljjceG1WdN0YV+hHkUwcbkIdefAPBNY89oJ60STI0lhBs3VDZPX2C4DnTg=,iv:kP4i8pRHpnkrruKEZpsourkEHSkkAnbIe0cJ+I8GLTI=,tag:yKEV58tBrF4hmDGbjreUig==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-standard-cnpg-user
  namespace: servarr
stringData:
  username: ENC[AES256_GCM,data:FTPDIPJcxiAEoPIrjvlF,iv:3FGWO3G6vM3TmMO1PpLiee8hWRklgf2GIs1y2H9Y/JI=,tag:1CDo3y+2orYvi5Hs2octPw==,type:str]
  password: ENC[AES256_GCM,data:1KpQ7UgFnKmbF3DJ8Dzy,iv:2VPe7hkUBbHcMe37zT6MXopJIv0RLOaLsDsk023JG5Y=,tag:Q4oPZ58x3DKCts3ITnjeqQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMGV1bEZtWkVBcnhhSjlJ
        MG9UOFBPVWt5dWpoNlFWbkp4RUF5c3Z0bGlVCk5QZjlTd1Zxd0RtaWJoWnplelg4
        dUZPMTZKTFpOVkwyY1ZTODRGY3hMU2sKLS0tIHR4cm9GQU1veW9SQmljZG1JRUU2
        QjB5SXlYVFBiNXc3YXBDWkxFV1FERXMKRXE64akROnHJjGb50Ib8nNKaVnsyq5IE
        FNfOMwznnYDMRBhdLwbm1YHZwTgfQkv5cl4sWYFv/RAeKm4/Z/PbeQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:53Z"
  mac: ENC[AES256_GCM,data:Qgw9AYtVbYcd5VP+kphYvSDba7OnmvH53qmxbKXdYibJP5YuRj3rDrirdzeopeXnVDynw6h5iidzQJxBiy/oX6BBkiDu70Ym0aWeAMtcQySoHvJDKljjceG1WdN0YV+hHkUwcbkIdefAPBNY89oJ60STI0lhBs3VDZPX2C4DnTg=,iv:kP4i8pRHpnkrruKEZpsourkEHSkkAnbIe0cJ+I8GLTI=,tag:yKEV58tBrF4hmDGbjreUig==,type:str]
  version: 3.13.3
