apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-api-key
  namespace: servarr
stringData:
  key: ENC[AES256_GCM,data:T0LX2jPAAuryN0v75NZfCtjTDq0kaFmsZKh6hHS11Ag=,iv:8i5BMPCdRzkFTV4+AYdT7+IbkjSrgESiBQQuyhTQhRY=,tag:6BhHxPx04pu9GmOf5WyHtg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR3VZTm1pVHpIN3hNbVVP
        YkVIMk14WmhXTHQ0NjNBdHdYYW1ic2lTSTBzCmtXK0FXd3NidjBRY3BZU0twWGgy
        eVE2WndvSkNIRU5ZOVVMeEJaZGRBeEEKLS0tIG92MGdSN2R2NlRMNUQvbkxWc2pW
        RGJaYmd3b3lET0dRdWoxZHpiVjhZZk0KrENa7OYrGrSvzs3qbw0xe3g9hkJuYImn
        haYEg3nJ7pd0UmDdXb/cMZfr6Bpl6AkAisJg5MERlqX9cXnf2hKS9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:54Z"
  mac: ENC[AES256_GCM,data:r3utG4eCianXGY1O2XKG4dPZvX8cyYf2oNJqj3/LApQwj+nmwddsLXcw/KsYRIadS5+9uatBiU54ttSu7WevQ3z9AgxYbdYCwlGlaJw2Eu6IQgRdXLBJ9Bk4alvpN07X9UiQc9EwZKFO8JlEw0uv7SAv1Co/1xtWosatcvBokpM=,iv:cOSPL5TYvOwhdUnXNMVxwg5HzPSEJaZUpxoRwVNfcXo=,tag:uaUftLHa+qY1Sty9ltnyoA==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-oidc
  namespace: servarr
stringData:
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:rYIzETL/D1TWNedt1La5SyfsU2DqLBj12ocXta/hJoDax+e9narTHsiwM2s=,iv:usTS9X1EyZ9bAQn53gAtyj+gnkkUj8efEv0D3aNUO7A=,tag:Te9oITcoNouPDqCb+XAdSQ==,type:str]
  CLIENT_SECRET: ENC[AES256_GCM,data:fZeDCX4AL+XHvieKGRZ04AvqV/JXq3YbbnQa2wlqKdGZMbQhM8WayE2P9z1KIBaG,iv:bScByzh+hEFkdgUW50ZZrXp1RLpGYfLO+ksIkhlA8I0=,tag:kCQfimLsuGcnzO5ERoMuAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR3VZTm1pVHpIN3hNbVVP
        YkVIMk14WmhXTHQ0NjNBdHdYYW1ic2lTSTBzCmtXK0FXd3NidjBRY3BZU0twWGgy
        eVE2WndvSkNIRU5ZOVVMeEJaZGRBeEEKLS0tIG92MGdSN2R2NlRMNUQvbkxWc2pW
        RGJaYmd3b3lET0dRdWoxZHpiVjhZZk0KrENa7OYrGrSvzs3qbw0xe3g9hkJuYImn
        haYEg3nJ7pd0UmDdXb/cMZfr6Bpl6AkAisJg5MERlqX9cXnf2hKS9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:54Z"
  mac: ENC[AES256_GCM,data:r3utG4eCianXGY1O2XKG4dPZvX8cyYf2oNJqj3/LApQwj+nmwddsLXcw/KsYRIadS5+9uatBiU54ttSu7WevQ3z9AgxYbdYCwlGlaJw2Eu6IQgRdXLBJ9Bk4alvpN07X9UiQc9EwZKFO8JlEw0uv7SAv1Co/1xtWosatcvBokpM=,iv:cOSPL5TYvOwhdUnXNMVxwg5HzPSEJaZUpxoRwVNfcXo=,tag:uaUftLHa+qY1Sty9ltnyoA==,type:str]
  version: 3.13.3
