apiVersion: v1
kind: Secret
metadata:
  name: radarr-standard-api-key
  namespace: servarr
stringData:
  key: ENC[AES256_GCM,data:xtGue3ylJcz5/Y/oauNX80T8YiLIHYU5lLJRVTQ40/M=,iv:Lhd7VmXC0G6LxyUxvd4qb6zgv5oNoZFBCsS7PxbUDcg=,tag:IeD+0RzO4XZzQS9eQOn0uA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a2NicURUQjFTdC93TGxx
        eFZqdFE3ZDZQSGpRdklqQXRJUG9MaFhjcG1nCnowamxwNmZwNytZVHVNTWNJczVY
        ZGZRYkkwSUxhV1lBUERENjBTNy9iSXMKLS0tIHhXVnJEbWwrZzd4V1kvakd5cGgw
        clFCMzZpdEVWNzMyaFE2aUUvMkg3eW8KObX8e/X+YepYdAzAkf/bM2SogDkmw24M
        2YOm5HOHpJ0+REbXkbJAzwhshSfdJeRgDF2IZr4/QQjWAY8xg1o3CA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:55Z"
  mac: ENC[AES256_GCM,data:fh0N05yAKEWaSRT03ki3K6MJAg2fNKY7v+FYEVJl/4L7Z9W9QH+sq99aj1w8OpQFGAVg8zyo4dKnfjp/0Gg9UKcJs0kGmbEYbQbyGTKc7dOjcmWSZ2ufl0dS+VRch16qFHMteyqZQvFMHmRvlAedWhTmneBax2+zu9pIbG+APZE=,iv:da/4Bk9ZC05CiVvh6irz+UyUjneYiFpJoyHVnS2IQIs=,tag:g6L94go2rl6nKCWvM3BhHw==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-standard-oidc
  namespace: servarr
stringData:
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:Ff7UeWDNQHcxwzsd/z/k50/7uzfkBH2nB3jdxqTSrZABHmQMIJxNRJMN8nY=,iv:gNYZjZxw9QcQxArxVdwtYU7pXd6SIWaSPHUIfSbH06Y=,tag:fzxyQOPFnUy4CbFZ9Oh/CQ==,type:str]
  CLIENT_SECRET: ENC[AES256_GCM,data:QEUiSRYTsxTOaKcP0Xe69bNoqrjGSZU0YbIJXmaISzXmjr0LMYF/KmB0V0Ur1Gh8,iv:dzAwG3Ov2usYffdh2k+laMIUIH4rAyWWROmaCQHIVWM=,tag:TkLyyoMvbAEbZWwfMkvmrg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a2NicURUQjFTdC93TGxx
        eFZqdFE3ZDZQSGpRdklqQXRJUG9MaFhjcG1nCnowamxwNmZwNytZVHVNTWNJczVY
        ZGZRYkkwSUxhV1lBUERENjBTNy9iSXMKLS0tIHhXVnJEbWwrZzd4V1kvakd5cGgw
        clFCMzZpdEVWNzMyaFE2aUUvMkg3eW8KObX8e/X+YepYdAzAkf/bM2SogDkmw24M
        2YOm5HOHpJ0+REbXkbJAzwhshSfdJeRgDF2IZr4/QQjWAY8xg1o3CA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:55Z"
  mac: ENC[AES256_GCM,data:fh0N05yAKEWaSRT03ki3K6MJAg2fNKY7v+FYEVJl/4L7Z9W9QH+sq99aj1w8OpQFGAVg8zyo4dKnfjp/0Gg9UKcJs0kGmbEYbQbyGTKc7dOjcmWSZ2ufl0dS+VRch16qFHMteyqZQvFMHmRvlAedWhTmneBax2+zu9pIbG+APZE=,iv:da/4Bk9ZC05CiVvh6irz+UyUjneYiFpJoyHVnS2IQIs=,tag:g6L94go2rl6nKCWvM3BhHw==,type:str]
  version: 3.13.3
