apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: recyclarr-secret-overlay
  namespace: servarr
stringData:
  secrets.yml: ENC[AES256_GCM,data:anPtskRRXLEKbQlPkvYZIdE8+455a/9y7baI7y1t1aStISC0G5T2brB6TB9EYH0W7pspRyr0+zgauLMzY+1DUUiqFKwDnfzRdzOBc70DRFM7Dwye3tCIjvQXyRrOkBglpONuGxQov4CVUtxl/zJtpjfFdk756vUCKXwOObxoGfgwLZpuDvRU0S+/UFWRTgqqjohVlTmfTOsoRSRBJUzqR+Pe/Ar159Jwl7fR,iv:PfQ6OZDbSyh3dfYJSUMJnJHvfaQeI+IeEBL73bD6uZA=,tag:DC965QqkJ5yF3F9QHsgZQQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMzFML3ZxMTkwR2hVaWFC
        L25xZytPczNUcVkvckM4L1FTWE0vb2paYUVnCkpjTDRuMGdjNTZ3bFVCUmFVWWRi
        dUhpVk1raXVFVE5ZU01oZmwxTFFOQzAKLS0tIEowcGNWRWc2R0hSM0w2MkZHc1lv
        ckdhbEJ2Y0pIZHhsT3JkT2MyalNxQmMKgi3N2nwv0z5LztsxOQZG2bGYQQuXvUFI
        3XY1xaffJrjcTMxSOdnqdkBsMIw3A+yukGltaGmdhuPZzbHaYddDuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:10:04Z"
  mac: ENC[AES256_GCM,data:Wlw0dpXr22LeN/zTGamm6Fs5reyQZXiRdWQpH9T5uBsJCNkMpky2ysBrALG/ZBpHaRTRTWjmZJnDHa7Oyzzw/YVqlAcV2oImEKfgX2vwQvgQuDQrkeSDJg8zxL3xe9dQI3EWZnM+cEn0LP29SOC1yIwXXdDf9b+kFXRmE9mgbTs=,iv:IsPXULYHxhCW8qEM4VkRR8CiqAqs1rDwTbYMREXDIug=,tag:Hx92Oh9+gRTEDSQ9+FqKKQ==,type:str]
  version: 3.13.3
