apiVersion: v1
kind: Secret
metadata:
  name: sonarr-anime-api-key
  namespace: servarr
stringData:
  key: ENC[AES256_GCM,data:njG6Y4TvMC5TIMRtRr1w2n5RdCvRdsjRpW/NJx0rE34=,iv:bainc7jrR8cFQB9vhu9oKJ7QdMIim2dCFkWxVSXWm8U=,tag:CQoN4l2/wtPrUCRFtLPigw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUVU2MmdVajVyRHVrVXgr
        YTlCb1E1Wndid2tHNk1md1Y4cStuSWliK1dZCmdlZm1TYkpudEhXckZsbVFxeW5w
        L1ZDUXUrK2o1b2lscUlYSklSSHhzdHcKLS0tIG5UcVg4ZDh0VzJRVlY1L0xENmRt
        blk0UW5QVUNCellZMnB2em8vYms2NUkKGSMb2xcW2zVGSr3vib0bjaHQ60mwVYdm
        ofaPyqCr345t6tF/HZszqlSqEZGCxjP/dTLPT3HYhj5TxMLLshn0Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:57Z"
  mac: ENC[AES256_GCM,data:l4i3yr6kbjMMcR/aYp2zPX+sXRdUjdDuCE25jifXuw9QrBILVgMmf/ABeSCeG7GSElG38YUNrN8snj35nuKFMvzGdPOVL+xb85+2/KcLS12qO87IQPsUywpReLf3SGY4oVTURJncEudStWyZJt2k/sa6xMRy7DLtGsxzLGZfopg=,iv:azCSl2BhN3cy4da3DCBfCqwcN0FdOD0nXV9avNQVs8Y=,tag:PFRGcPGMSaS/GxzO32fdjg==,type:str]
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-anime-oidc
  namespace: servarr
stringData:
  SESSION_ENCRYPTION_KEY: ENC[AES256_GCM,data:Rdu5bZv2i/4O3dt42Inf0ewk9e5PldyYPhTnsNxO3i50SAgBF9jD5wRLWcE=,iv:bpRkmFFjGeV45NqpyXG+Ge2yzui+r6tRRsJJYJqGAMM=,tag:Fw8Vezu0VOwgoL9742tSbA==,type:str]
  CLIENT_SECRET: ENC[AES256_GCM,data:6srVZn1Amj8ajD1BbsRb+kKb96salmp8bdwDVELyuYQ+HG0MDvDB/3EvxsTwXIxX,iv:d6bTm0HlNm/dTR6NusKdkZzHr3Vx5JxokNp/UzzsBFg=,tag:4KMmrrKeu/HBX21fiw1smg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUVU2MmdVajVyRHVrVXgr
        YTlCb1E1Wndid2tHNk1md1Y4cStuSWliK1dZCmdlZm1TYkpudEhXckZsbVFxeW5w
        L1ZDUXUrK2o1b2lscUlYSklSSHhzdHcKLS0tIG5UcVg4ZDh0VzJRVlY1L0xENmRt
        blk0UW5QVUNCellZMnB2em8vYms2NUkKGSMb2xcW2zVGSr3vib0bjaHQ60mwVYdm
        ofaPyqCr345t6tF/HZszqlSqEZGCxjP/dTLPT3HYhj5TxMLLshn0Gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-06T07:08:57Z"
  mac: ENC[AES256_GCM,data:l4i3yr6kbjMMcR/aYp2zPX+sXRdUjdDuCE25jifXuw9QrBILVgMmf/ABeSCeG7GSElG38YUNrN8snj35nuKFMvzGdPOVL+xb85+2/KcLS12qO87IQPsUywpReLf3SGY4oVTURJncEudStWyZJt2k/sa6xMRy7DLtGsxzLGZfopg=,iv:azCSl2BhN3cy4da3DCBfCqwcN0FdOD0nXV9avNQVs8Y=,tag:PFRGcPGMSaS/GxzO32fdjg==,type:str]
  version: 3.13.3
