---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dedicated-server-abiotic-factor
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s

  values:
    global:
      alwaysAppendIdentifierToResourceName: true

    controllers:
      dedicated-server-abiotic-factor:
        type: statefulset

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: &PUID 1000
            runAsGroup: &GUID 1000
            supplementalGroups: [568]
            fsGroup: *GUID
            seccompProfile:
              type: RuntimeDefault

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: vonarx.online/cpu-capacity
                        operator: Gt
                        values:
                          - "5"
                      - key: vonarx.online/memory-capacity
                        operator: Gt
                        values:
                          - "10240"

              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: vonarx.online/cpu-performance
                        operator: In
                        values:
                          - high
                - weight: 10
                  preference:
                    matchExpressions:
                      - key: vonarx.online/memory-performance
                        operator: In
                        values:
                          - high

        containers:
          dedicated-server-abiotic-factor:
            image:
              repository: ghcr.io/joker9944/abiotic-factor-server
              tag: 1.0.3@sha256:80d90e0b18a48a9d3ba2a678fcd884da26b27d77d113c27192456dc1fe2daf5b
            env:
              ADDITIONAL_ARGS: -PlatformLimited=PC
            envFrom:
              - secretRef:
                  name: dedicated-server-abiotic-factor
            resources:
              # requests = limits for Guaranteed QoS
              requests:
                cpu: 4
                memory: 4Gi
              limits:
                cpu: 4
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

        initContainers:
          steamcmd:
            image:
              repository: ghcr.io/joker9944/steamcmd
              tag: 1.0.0@sha256:ea8c2c77866092cd708770606676555cf80235b5ea3173442a1ebeea184dcea0
            args:
              - +@sSteamCmdForcePlatformType windows
              - +login anonymous
              - +app_update 2857200 validate
              - +quit
            resources:
              # requests = limits for Guaranteed QoS
              requests:
                cpu: 1
                memory: 2Gi
              limits:
                cpu: 1
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      dedicated-server-abiotic-factor:
        controller: dedicated-server-abiotic-factor
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.0.131
        ports:
          game:
            port: 7777
            protocol: UDP
          query-tcp:
            port: 27015
          query-udp:
            port: 27015
            protocol: UDP

    persistence:
      steam:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 20Gi
        globalMounts:
          - path: /home/steam

      saved:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        retain: true
        size: 2Gi
        advancedMounts:
          dedicated-server-abiotic-factor:
            dedicated-server-abiotic-factor:
              - path: /home/steam/.steam/steam/steamapps/common/Abiotic Factor Dedicated Server/AbioticFactor/Saved

      tmp:
        type: emptyDir

    rawResources:
      source-saved:
        enabled: true
        apiVersion: volsync.backube/v1alpha1
        kind: ReplicationSource
        spec:
          spec:
            sourcePVC: dedicated-server-abiotic-factor-saved
            trigger:
              schedule: "@daily"
            restic:
              repository: dedicated-server-abiotic-factor-restic-saved
              pruneIntervalDays: 7
              retain:
                daily: 7
                weekly: 4
              copyMethod: Clone
              storageClassName: longhorn-local-lax
              cacheStorageClassName: longhorn
              moverSecurityContext:
                runAsUser: *PUID
                fsGroup: *GUID
                runAsGroup: *GUID
