apiVersion: v1
kind: Secret
metadata:
  name: openaudible-restic-config
  namespace: openaudible
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g7oh7cRSrI/tjenVs60ix/0c6WDneTbtnF92rw==,iv:1pEBbxMMnhQjLPeacWj070wlUg+EBEBdcMnS4c6c/pI=,tag:77mlsPZYSl339t1rFcRfYA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BcO3MnfNMjE6Gz1i+Nwf3CE/SnGsMhDEbQgeiVJVwWU0aFimFlk2ie6jUTJ0F9P7fTN2weY=,iv:nGBdqni0kBdDmabm7CWzJ4zYtHUat7MyqyPR770EMT0=,tag:7MzTo1P7D3pgoPG6eRSEBw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:SE1+xOuTRF0g7szFVTXqQm9zHqQ=,iv:BhkmhHNHq+B1MMnjGZKFR3qzovFbZYyYPeTAVxpjxz4=,tag:3FwH96t3cpOXrHn4Kpw8Xw==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:gJ+zsLxqiobyzAcpgEcasUiuDVeb5EDDWDrLnmrIgli/BmBdXrHw9xTj+vAq7O0pGOyv+td5LR8YdY6f3/4RgiQo,iv:2j9pbrFtNfsQ5t3wuIuZcFofdRmUOXtFDDaOzeqAjZU=,tag:/+0VIDnipXH4z9EnLgqi0Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWUtRUDhVaERJU3NETk5t
        SEljNUtrWmZYV0ExUm9oKzFpSlN0Wmx4ZXlNCjZYTEU5clkwR3pXajBWS3BvelNY
        cXhreEhGOFJpSXVKS0VOckR0eGF5UE0KLS0tIFgvNlJWR25TVjNtaHJiUGFzT2lw
        ei9lREtqbk5LUFZKcTR0R2V1cm8zNlUKekUClLQBxUzkiO9b8Z4iRBvDd5T5IEIZ
        Pf1tu1VSGhfE2uWhPgPHqEUEbnkWzco/YGeVnT5MnmcD+UZEf/bTJQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-07T19:04:07Z"
  mac: ENC[AES256_GCM,data:efWKQybYlx53IyGq1F7tFm4qP7TC6CURqpF596LeKbKFKyq9eqNGIjPoDbk6rfDNd9JjskRpmvkpX9ipafDWB+xlEkOmPapJvSyPX+hl/37MPq/TkRAxESNuJ0dbfDI1r9aGsQqxw0mWSX6N9QAtkA+lbgq70HiOORakV5R9fjU=,iv:+XdVP5PV9Z0AJyhIcyAEXxOwAsBsICFAvCA0byifmuc=,tag:2L7OdrAtuI0GopbRqAbPwg==,type:str]
  version: 3.13.3
