name: docker-publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - flake.lock
      - images/**

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - attr: .#abiotic-factor-server
          - attr: .#steamcmd
          - attr: .#gotify-custom
          - attr: .#jinja-cli
          - attr: .#postgresql-client

    steps:
      - name: Repository checkout
        id: git-checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # cSpell:ignore cachix
      - name: Install nix
        id: nix-install
        uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0

      - name: Install skopeo
        id: skopeo-install
        shell: bash

        run: nix profile add nixpkgs#skopeo

      - name: Install jq
        id: jq-install
        shell: bash

        run: nix profile add nixpkgs#jq

      - name: Install cosign
        id: cosign-install
        shell: bash

        run: nix profile add nixpkgs#cosign

      - name: Build image tarball
        id: nix-build
        shell: bash

        run: nix build -L ${{ matrix.attr }}

      - name: Extract image metadata
        id: image-metadata
        shell: bash

        run: |
          IMAGE=$(tar -xOf ./result manifest.json | jq -r '.[0].RepoTags[0]')

          IMAGE_NAME="${IMAGE%%:*}"

          IMAGE_TAG_PATCH="${IMAGE#*:}"
          IMAGE_TAG_MINOR="${IMAGE_TAG_PATCH%.*}"
          IMAGE_TAG_MAJOR="${IMAGE_TAG_PATCH%%.*}"

          echo "image-name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "image-tags=latest $IMAGE_TAG_MAJOR $IMAGE_TAG_MINOR $IMAGE_TAG_PATCH" >> "$GITHUB_OUTPUT"

      - name: Publish image tarball
        id: skopeo-copy
        shell: bash

        run: |
          DEST="${{ env.REGISTRY }}/${GITHUB_REPOSITORY_OWNER,,}/${{ steps.image-metadata.outputs.image-name }}"

          for IMAGE_TAG in ${{ steps.image-metadata.outputs.image-tags }}; do
            if [[ ! -n ${DIGEST:-} ]]; then
              skopeo copy \
                --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
                --digestfile digest.txt \
                "docker-archive:./result" \
                "docker://$DEST:$IMAGE_TAG"

              DIGEST="$(tr -d '\r\n' < digest.txt)"
              echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
            else
              skopeo copy \
                --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
                "docker://$DEST@$DIGEST" \
                "docker://$DEST:$IMAGE_TAG"
            fi
          done

      - name: Sign tags
        id: cosign-sign
        shell: bash

        run: |
          DEST="${{ env.REGISTRY }}/${GITHUB_REPOSITORY_OWNER,,}/${{ steps.image-metadata.outputs.image-name }}"

          for IMAGE_TAG in ${{ steps.image-metadata.outputs.image-tags }}; do
            cosign sign \
              --registry-username "${{ github.actor }}" \
              --registry-password "${{ secrets.GITHUB_TOKEN }}" \
              --yes "$DEST:$IMAGE_TAG@${{ steps.skopeo-copy.outputs.digest }}"
          done
